### ISSUE TITLE
Clicking to the right of a min/max range moves the minimum handle

### ISSUE THREAD

**Issue by coxm** [rzajac/angularjs-slider#101]
I'd expect it to move the max handle instead; can you confirm if this the intended behaviour?

**Comment by ValentinH** [comment]
Indeed this would be the best behaviour. It needs a little more work to be like this... ^^ 
For now, a click on the bar just move the min handle but some logic should be added to check which handle to move...

**Comment by coxm** [comment]
OK. I have a fix for this now, but it uses the `getEventX` method from PR #100. I'll file another PR when that one is closed.

**Comment by ValentinH** [comment]
Great!

**Comment by ValentinH** [comment]
Closed by #105 merge
