### ISSUE TITLE
rz-slider-on-change fires before value is changed

### ISSUE THREAD

**Issue by kritollm** [rzajac/angularjs-slider#106]
$scope.onRzSliderChange = function (value) {
            console.log('changed', $scope.rzProfitSlider);
        }

Is logging the old value

**Comment by ValentinH** [comment]
Indeed. Let me fix this ;)

**Comment by sebastialonso** [comment]
Is anybody still having issues with this? After getting version 0.1.26?

**Comment by ValentinH** [comment]
Indeed the version number are messy... The source file should be OK for this issue and I think the minimized one too but let me check tomorrow (not at work anymore for today).

**Comment by sebastialonso** [comment]
Thanks for you quick answer and for the awesome module.

Just to check If what I'm trying to is wrong I started playing with the fiddle, which links to last version on Github.

![fiddle example](https://cloud.githubusercontent.com/assets/3493453/9452380/41cd6b06-4a8a-11e5-9877-7273da1caff1.gif)

Is this part of the design? Notice how `otherVariable` needs another input from the user to the slider, just to achieve the value it should had achieved on the previous input. I have been on this for hours so I apologize if I'm making a mistake here.

**Comment by ValentinH** [comment]
Could you add the jsfiddle link please?

**Comment by sebastialonso** [comment]
Here you go http://jsfiddle.net/pq7yr6d6/52/

**Comment by ValentinH** [comment]
This is good now there was indeed still an issue.

**Comment by sebastialonso** [comment]
Great. Thanks!
