### ISSUE TITLE
Left limit label shows after 'rzSliderForceRender' with closes value

### ISSUE THREAD

**Issue by artaommahe** [rzajac/angularjs-slider#108]
If slider is hidden and shows after some actions with 'rzSliderForceRender' event broadcast, and slider value is near slider limits, then left limit label does not hide(but right limit label is hidden)
![example](http://i.imgur.com/tDiLOYT.png)

**Comment by ValentinH** [comment]
Could you please provide a JSFiddle reproducing this issue please? You can fork this one: http://jsfiddle.net/pq7yr6d6/

**Comment by neversun** [comment]
I have the same problem and created a codepen based on your pen as of https://github.com/rzajac/angularjs-slider/issues/79#issuecomment-125971572:
http://codepen.io/anon/pen/OyVzVx?editors=101

**Comment by ValentinH** [comment]
Thanks, I'm looking into it. ;)

**Comment by ValentinH** [comment]
@neversun on the codepen, you should replace rzCalcViewDimensions by rzSliderForceRender.

**Comment by neversun** [comment]
Thanks for updating the demo. Works now :+1: 

Just in case anyone is using `angular-ui/bootstrap`:

    modalInstance.rendered.then(function (event, args) {
      $timeout(function () {
        $scope.$broadcast('rzSliderForceRender');
      });
