### ISSUE TITLE
Variable Steps in ng-repeat Loop

### ISSUE THREAD

**Issue by nwestbury** [rzajac/angularjs-slider#109]
I'm an angular noob so sorry if this isn't an actual issue but rather misuse.

I need to create many sliders with different step sizes for each (varying from a small decimal number to large ints). I tried to put it in a ng-repeat loop but get a NaN when I put anything other than a hard-coded number in the step (except for start/end). When I replace att.step with "1", say it works fine.

See this behavior in this fiddle: [FIDDLE](http://jsfiddle.net/Guy3000/pq7yr6d6/93/).

Any suggestions or is this a bug?

**Comment by ValentinH** [comment]
See #103

**Comment by nwestbury** [comment]
@ValentinH Using {{}} around the step size works great, thanks!
