### ISSUE TITLE
Two nodes of range slider collide with each other

### ISSUE THREAD

**Issue by VolvoOlympian** [rzajac/angularjs-slider#110]
I am using the range slider with ionic. When selecting the range of the slider by dragging the two slider nodes, then going to the next page with $state.go and clicking the standard back button on the header bar to return to the previous page where the range slider is located at, the two nodes of the range slider overlaps with each other.

Is there any workarounds I could try to solve this?

**Comment by ValentinH** [comment]
Could you please provide a fiddle showing this issue? (Please fork this one: http://jsfiddle.net/pq7yr6d6/)

**Comment by ValentinH** [comment]
By the way, I'm pretty sure that you should do this: https://github.com/rzajac/angularjs-slider#slider-events
see also #79...
