### ISSUE TITLE
rzSliderPresentOnly attributes

### ISSUE THREAD

**Issue by fabienL** [rzajac/angularjs-slider#113]
I'm using range slider and i try to attach scope value to the attr rzSliderPresentOnly.
My example : 
Directive : 
rzslider(rz-slider-model="formData", rz-slider-floor="0", rz-slider-present-only="readonly", rz-slider-ceil="100", rz-slider-always-show-bar="'true'")
Controller : 
$scope.readonly = true;

 I changed 
this.presentOnly = (attr.rzSliderPresentOnly === true);
by 
this.presentOnly = (scope.rzSliderPresentOnly === true);

and in scope declaration : 
 rzSliderPresentOnly: '@',
by
 rzSliderPresentOnly: '=',

Example : http://jsfiddle.net/qv6cs01m/

**Comment by ValentinH** [comment]
Actually you can get it working using the `{{ }}` syntax: http://jsfiddle.net/f0rL32hy/.
But you will not be able to change it at runtime. This is the same issue than #103 for step or  precision...
