### ISSUE TITLE
sliding towards the end the ceil value get hide 

### ISSUE THREAD

**Issue by secabhi** [rzajac/angularjs-slider#114]
hi . I don't know whether this is an issue or its supposed to be work like that . BUt when i slide slider towards the ceil value the ceil value get hide . Is there anyway to fix it . 

http://jsfiddle.net/pq7yr6d6/

In this fiddle when i drag slider above 434 value the ceil value get hide . i think ceil value shouldn't hide and when the max value becomes equals to ceil value max should hide .. I want this to be done without onchange event . any attribute i can use .. plz help

**Comment by ValentinH** [comment]
I think it is on purpose in order to prevent the value label from overlaping with the max one.
If you want, you can use the `rz-slider-hide-limit-labels` attribute to hide the min/max labels and then display them yourself like in this example: http://jsfiddle.net/me5py7m1/ . Once you got this, you can position/hide them to ensure that they don't overlap.

**Comment by secabhi** [comment]
thanks valentine, but i m facing one more problem i.e my min and floor value both are zero . but i am not able to see the slider floor value . Can this happen ?

**Comment by ValentinH** [comment]
Could you provide an example, I don't see what you mean.

**Comment by secabhi** [comment]
thx valentineH . I fixed that issue it was not rendering properly .
now i have a question can i set minimum interval between min and max value even if i am setting min == max . ex - my min = 0 max = 7 by dragging i set min  = 7 . now i want if u can help me to reset the value with minimum diff 1

**Comment by ValentinH** [comment]
You can use `rz-slider-on-end` callback function to do your custom logic at the end of the slider move, like resetting the min to 0
