### ISSUE TITLE
[refactor request] can I do some refactorization and improvement

### ISSUE THREAD

**Issue by e-cloud** [rzajac/angularjs-slider#118]
there are some point i want to improve:
* add `umd` support
* add *templateCache plugin* to collect the html, it's not nice to write html in `.js` file
* remove the annotation code, and pass it the `ngAnnotate` as for source code doesn't need to be annotated when developping
* [optional] give up `grunt` and be in favor of `gulp`

**Comment by e-cloud** [comment]
Another question
why do these codes exist?
https://github.com/rzajac/angularjs-slider/blob/master/rzslider.js#L1256-L1287

anyway, which IDE do you use? @rzajac

**Comment by ValentinH** [comment]
- add umd support
> yes

- add templateCache plugin to collect the html, it's not nice to write html in .js file
> yes

- remove the annotation code, and pass it the ngAnnotate as for source code doesn't need to be annotated when developping
> yes

- [optional] give up grunt and be in favor of gulp
> I think that for now, since grunt do everything we need, we don't need to give it up...

Thus, a PR is always welcome. :)
