### ISSUE TITLE
Bubble positions all wrong

### ISSUE THREAD

**Issue by akarl818** [rzajac/angularjs-slider#12]
The bubble on the top of the pointer isn't positioned correct until slided all the way to the left.

The position of the left bubble does not dissapear.

The position of the right bubble is outside the container.

![screen shot 2014-03-19 at 11 23 17](https://f.cloud.github.com/assets/2255219/2458753/89cd65f4-af50-11e3-8fbf-3279cc9f3bec.png)

**Comment by rzajac** [comment]
This should be fixed with new css styles
