### ISSUE TITLE
Put this on npm!

### ISSUE THREAD

**Issue by Pritoj** [rzajac/angularjs-slider#120]
Hey, please put this on npm and bower.. package management will be easier :)

**Comment by ValentinH** [comment]
I have never done this before, any advice?

**Comment by kukac7** [comment]
@Pritoj bower: https://github.com/rzajac/angularjs-slider/blob/master/bower.json

**Comment by ValentinH** [comment]
I published it here: https://www.npmjs.com/package/jusas-angularjs-slider
