### ISSUE TITLE
[FEATURE REQUEST] Slide end function

### ISSUE THREAD

**Issue by Pritoj** [rzajac/angularjs-slider#121]
Please add a feature to call a function on slide end and not just slide change. I know this can be achieved via the "slideEnded" event, but I don't know which slide has ended. I would want to customize the function based on which range was used so this would be uber-helpful.

**Comment by ValentinH** [comment]
OK so you would like the same implementation as the slideChange function?

**Comment by Pritoj** [comment]
Yep.
I'll explain the use case.

So I have a list which updates based on the filter. If I use the "change" function, it runs while sliding, so I get multiple requests to the same API. What I really want is the final value.

**Comment by ValentinH** [comment]
There is now a on-start and on-end callback that can be used as the on-change one. ;)

**Comment by Pritoj** [comment]
Awesome man, such quick response was not expected! Simply brilliant!
