### ISSUE TITLE
rz-slider-step as values

### ISSUE THREAD

**Issue by wowDaiver** [rzajac/angularjs-slider#126]
It is work - http://jsfiddle.net/wowDaiver/pq7yr6d6/157/
It is not work - http://jsfiddle.net/wowDaiver/pq7yr6d6/158/

Difference in line  rz-slider-step="{{vm.priceSlider.step}}"

It don't difficult, but I forget every time ((

**Comment by ValentinH** [comment]
Yes I know. #103
