### ISSUE TITLE
Release 1.30 broke bower dependency

### ISSUE THREAD

**Issue by SidhNor** [rzajac/angularjs-slider#127]
In release  1.30 - rzslider.js file moved to dist folder and is no longer available in root folder as specified by bower.json
```
"main": ["rzslider.js", "dist/rzslider.css"],
```

**Comment by ValentinH** [comment]
You're right. Sorry for that. It should be fixed now.

**Comment by SidhNor** [comment]
Was the 1.30 release on bower updated?

**Comment by ValentinH** [comment]
I don't know how to do it! ^^ But when I do bower install on my local, all the files are there...

**Comment by SidhNor** [comment]
As far as i understand bower is pulling the tag, which does not contain the fix.

**Comment by ValentinH** [comment]
It seems that I was forced to push a new release. 0.1.31 should be OK.

**Comment by SidhNor** [comment]
This fixed it. Our CI is back to green now. Thanks for the quick update.

**Comment by ValentinH** [comment]
You're welcome. And sorry for breaking you CI!
