### ISSUE TITLE
Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite

### ISSUE THREAD

**Issue by bashekking** [rzajac/angularjs-slider#13]
It seems that it doesn't play well with angular 1.2.15 on my system

Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite! See: http://docs.angularjs.org/api/angular.element
http://errors.angularjs.org/1.2.15/jqLite/nosel

**Comment by akashnautiyal013** [comment]
plz! help same here

**Comment by ValentinH** [comment]
Please provide a JSFiddle sowing the issue....

**Comment by akashnautiyal013** [comment]
fixed the problem u have to load jquery script before angular.js

**Comment by akashnautiyal013** [comment]
in index.html

**Comment by haiquan** [comment]
@akashnautiyal013's answer is right. It works in my project. Thanks.
