### ISSUE TITLE
Keep button inside the slider bar.

### ISSUE THREAD

**Issue by cycustodio** [rzajac/angularjs-slider#130]
Thanks for making this directive. 

In our implementation, we have both text input and the slider as alternative inputs. The issue is when people write values in the text input greater than the slider max or less than the slider min; the button goes past the slider bar. 
https://jsfiddle.net/6ra6y53e/2/

Is there a way to keep the button within the bar and display the value regardless of the min/max?

**Comment by ValentinH** [comment]
I think it is not really the role of the slider to handle such a case. In the slider, we can add a check to prevent the value to update but then if the ceil is 500 and the user types 2000, the slider will directly reset the model to 500...
