### ISSUE TITLE
Labels get past slider width if too big

### ISSUE THREAD

**Issue by karelcallens** [rzajac/angularjs-slider#131]
Hello,

Love the slider! I also use it for datefilters. In that setup labels tend to get too long and get past the slider width. This is messy especially if you use 'overflow:hidden' in the element that contains the slider.

By changing a little the setLeft for the Low, High and combined label on line number 690, 705, 799 using a minimum of 0 and a max of the barwidth - labelwidth, I achieve that behavior.

Might be interesting to include if wanted.

**Comment by ValentinH** [comment]
Could you please submit a PR and provide an example showing what it changes?

**Comment by ValentinH** [comment]
Let'c continue the discussion in #132 PR
