### ISSUE TITLE
Slider range can be draggable?

### ISSUE THREAD

**Issue by estvmachine** [rzajac/angularjs-slider#136]
Hi, i like ask if you can add the option of the slider can be draggable something like:

http://refreshless.com/nouislider/
http://ghusse.github.io/jQRangeSlider/

Thats all!, thanks for your time.

**Comment by ValentinH** [comment]
It's already available: http://jsfiddle.net/dw08mdb1/ .

You just need to add the `rz-slider-draggable-range="true"` attribute ;)

**Comment by estvmachine** [comment]
Thanks!! :+1:
