### ISSUE TITLE
How to Have set steps using rzslider?

### ISSUE THREAD

**Issue by TD89** [rzajac/angularjs-slider#137]
I want to know how I can have a slider starting at 0 and having different steps shown that a user can slide to? i also want to know if its possible to have a label that displays the current value under the slider bubble? Im stuck on how to do this and the help would be much appreciated.

**Comment by ValentinH** [comment]
Do you mean something like this: http://jsfiddle.net/464krvxm/ ?

If yes, this is a new feature brought by this PR: #68 if you like it, you can vote for it so it can be merged.

**Comment by TD89** [comment]
This is close to what I need. I want specific points though like 12, 18, 20, 30 etc? How can I go about doing that?

**Comment by ValentinH** [comment]
Do you want all the points to be visible?

Otherwise you can do this currently: http://jsfiddle.net/ay8utnkf/

**Comment by TD89** [comment]
no Just the points I need to get to, so the floor is 0 and the ceil is 18 I want users to be able to see points 12 and 16 and be able to click and go directly to that point. This is a scale asking how many years of school have you completed so (12-hs, 16-college, 18-gradschool). Im new to this angularjs stuff and you are helping me out a lot I appreciate it

**Comment by ValentinH** [comment]
So no, this is not currently possible.

There is also a PR for that (#92), but it it not finished yet. See this example: http://jsfiddle.net/257ynknz/

**Comment by TD89** [comment]
This is exactly what I want I just need to modify the ticks instead of 1,2,3 I want text is this possible within the directive? Thanks so much youve saved me so much time and stress lol Angular is so confusing at first.

**Comment by TD89** [comment]
This is exactly what I want I just need to modify the ticks instead of 1,2,3 I want text is this possible within the directive? Thanks so much youve saved me so much time and stress lol Angular is so confusing at first.

**Comment by ValentinH** [comment]
No the PR is not complete and the values shown on the slider are not using the translate function.

**Comment by TD89** [comment]
Ok cool, any timeline on when this PR will be complete?

**Comment by ValentinH** [comment]
I'm actually working on it right now to see if this could be done quickly...

**Comment by TD89** [comment]
Ok thanks, I stay posted

**Comment by ValentinH** [comment]
I just merge the first PR I mentionned in master and I add a rzSliderShowTicksValue attribute to show both ticks and their value.

Here should be what you want: http://jsfiddle.net/du9fL7kw/

**Comment by irhabi** [comment]
@ValentinH 
http://jsfiddle.net/du9fL7kw/ this example doesn't work on the latest version of your library.

**Comment by ValentinH** [comment]
What doesn't work?

**Comment by irhabi** [comment]
@ValentinH it doesn't work at all. There is an error...  toString()

**Comment by ValentinH** [comment]
In which browser? I'm testing it on my phone right now and it's OK..

**Comment by irhabi** [comment]
@ValentinH You're right! I was doing something wrong. It works fine! I'm sorry for the trouble :/
