### ISSUE TITLE
[FEATURE REQUEST] Add an option to show pointer on 0 value by default

### ISSUE THREAD

**Issue by soee** [rzajac/angularjs-slider#140]
Hi,

often we have range defined like [-100, 100] or [-233, 233] and it would be good to have an option to set pointer on 0 value position if ng-model value is not defined. At the moment pointer is always placed at the beggining of slider.

**Comment by ValentinH** [comment]
Actually, the pointer being on the left when there is no value is not a standard behavior but just an undefined behavior. 
The ng-model is a required field so if you want it to be at 0 on start, then you need to initialize it yourself.

**Comment by soee** [comment]
Well this will lead to setting and unsetting this value etc. Ok i'm closing it.
