### ISSUE TITLE
Change size of selected pointer leads to wrong calculation of left-position

### ISSUE THREAD

**Issue by flyingfeet** [rzajac/angularjs-slider#143]
Hey,

great directive!

But I need to change the size of the selected pointer. I tried to make it smaller overwritting the rz-pointer class. But then the left position is not correct. Is there a correct way to do it?
Is there also a way to remove the bar before the first and after the last item?

Thanks for your help!

**Comment by ValentinH** [comment]
Did you modify directly the CSS or the LESS file? Because in the LESS, you only have to change the variables defined at the beginning of the file...

**Comment by flyingfeet** [comment]
I modified the CSS directly, my fault. I didn't saw the less file!
