### ISSUE TITLE
Label translation with angular-translate

### ISSUE THREAD

**Issue by flyingfeet** [rzajac/angularjs-slider#144]
Hey,

I have another question. Is it possible to show translated labels? I only have the keys. So I have to use the $translate service. But this one is working with promises, so I have some timing issues when using it. Btw: the keys are coming from the server, so here I have also a delay...

Thanks for your help!

**Comment by ValentinH** [comment]
If you provide a custom translate function to the `rz-slider-translate`attr, you can do whatever inside it, you just need to return the current formatted label...

**Comment by flyingfeet** [comment]
Thanks, but the problem is, that the translate service returns a promise and I don't know how to handle it correctly.

**Comment by ValentinH** [comment]
You can write a function that calls the translate service, resolves each promise and stores the translation in a dict. Then the translate function of the slider reads this dict and returns the translated value if available else the original value.

**Comment by flyingfeet** [comment]
I tried that, but then I get following error in Firefox:
![image](https://cloud.githubusercontent.com/assets/3748388/10536121/d670fa34-73e8-11e5-993b-3c69ef661297.png)

and following error in IE:
![image](https://cloud.githubusercontent.com/assets/3748388/10536128/e3ee82c6-73e8-11e5-988e-a4bfea493cf9.png)

Chrome is working, like expected, correctly :)

**Comment by ValentinH** [comment]
Can you provide a JSFiddle showing the issue please? ;)

**Comment by ValentinH** [comment]
Closing as no update for more than a week.

**Comment by baffleinc** [comment]
Would very much like to know how this was resolved! I'm trying to use the slider as a price slider, however the gotcha is that I have to switch between currencies - therefore calculate the new currency. Rates come from an API, so stored in a promise.

**Comment by ValentinH** [comment]
Have you try to implement what I have suggested above?
