### ISSUE TITLE
one pixel difference between "Bar Fill" end and the handle start

### ISSUE THREAD

**Issue by oriprice** [rzajac/angularjs-slider#146]
http://jsfiddle.net/mq93ag31/1/

**Comment by ValentinH** [comment]
Well spotted! I'll look into that.

**Comment by emilmoe** [comment]
I think this one is closed :+1:

**Comment by ValentinH** [comment]
Indeed I fixed it myself by mistake in this commit: 819127a 
I had this code in my local repo when I tried your fix and forgot to remove it! ^^

**Comment by oriprice** [comment]
:+1:
