### ISSUE TITLE
Seperate less code from variables

### ISSUE THREAD

**Issue by emilmoe** [rzajac/angularjs-slider#147]
Can you seperate the code itself from the variable files?

I want:
variables.less
rzslider.less

So that my changes are not deleted when I update in bower or clone it to another computer.

**Comment by ValentinH** [comment]
Indeed this is a good point. Can you push a pull request?

**Comment by emilmoe** [comment]
I think I managed to do it:

https://github.com/rzajac/angularjs-slider/pull/148

**Comment by emilmoe** [comment]
I think something is wrong, or it's my bower installation?

When I run bower update the changes are not there. I also tried uninstall --save and install --save again, they are still not there.

**Comment by ValentinH** [comment]
I need to bump a new release version. At first, I wanted to wait to have more commits to add a new release, but if you need it now, I can do it.

**Comment by emilmoe** [comment]
I can understand that, I thought maybe you run major.minor.patch.

It's not a big deal for me, I can just make the change manually in my repo as long as I know you update it sometime soon.

**Comment by ValentinH** [comment]
As I didn't start this repo, I jsut keep following the logic with versionning. Indeed, we are at .35 which is quite big. Maybe, I will bump to 1.0.0 one day and then start using major.minor.patch versions which I think are good. 

I do the release now since we already did release for small changes...

**Comment by ValentinH** [comment]
Actually, I noticed that your last commit is uncorrect since the variable.less file is not included anywhere so the build fails. I'm fixing it and bupping a new release.

**Comment by emilmoe** [comment]
Thanks and sorry for the mistake. I'm not sure where you include them? I haven't posted many projects myself on GitHub so it was a little hazzle for me to understand it yesterday :-)

**Comment by ValentinH** [comment]
Tell me if you got the new release...

**Comment by emilmoe** [comment]
Thanks, it works now :-)
