### ISSUE TITLE
rz-slider-disabled

### ISSUE THREAD

**Issue by redhedded1** [rzajac/angularjs-slider#152]
It appears the value of the rz-slider-disabled attribute is only being checked on slider load. It would seem like it should be checked at slider end also. Programatically changing the attribute's value has no effect.

**Comment by ValentinH** [comment]
There is a watch on the disabled attribute so updating its value should work on condition that you do it inside a $digest cycle. See the last example on this page: http://rzajac.github.io/angularjs-slider/index.html

**Comment by ValentinH** [comment]
See this small (and stupid) example where I disable the slider on slider end: http://jsfiddle.net/kygfet8k/

**Comment by redhedded1** [comment]
Thanks very much. Learned something new about AngularJS as a result.

**Comment by ValentinH** [comment]
What did you learn? Can I add something to the doc to make it more obvious?

**Comment by redhedded1** [comment]
Well, I saw in the source code that you had setup a $watch. I needed to learn more about that and $digest and how it works. Your source code helps. (I also could have checked the demo page again for an example). Anyway, when I moved the line to disable the slider to my $scope.apply() fn. it worked. I think it should have been obvious from the docs and the source code, and especially the example. I think you added this functionality since I started using it in this project, so I didn't think to check the examples. Thanks again, you have done very nice work on this slider.

**Comment by sgarbesi** [comment]
@ValentinH Unfortunately this doesn't seem to work at all anymore?

See: http://jsfiddle.net/9nsnw8wn/

**Comment by ValentinH** [comment]
You are using the old API. You should check the doc

**Comment by sgarbesi** [comment]
@ValentinH I did. I'm assuming the `disabled` attribute was removed as a template option?

**Comment by ValentinH** [comment]
There is no template option anymore apart from rzSliderModel and rzSliderHigh. Everything goes into the rzSliderOptions attribute object
