### ISSUE TITLE
it's redundant to specify css classes with  tag name

### ISSUE THREAD

**Issue by e-cloud** [rzajac/angularjs-slider#154]
[see the code](https://github.com/rzajac/angularjs-slider/blob/master/src/rzslider.less#L32-L110)

As a third library, the css selectors' **weight(Specificity or priority)** ought to be **as low as possible**, which enables the users to override the default style to make some fantastic style easily. May be better render preformance.
of course, css classes with  tag name are also redundant. The code below is my recommendation.

redundant
```
...
span {
	properties...
	&classes{
		properties...
	}
}
...

```

better, low weight
```
...
span {
	properties...
}
classes{
	properties...
}
...
```

**Comment by ValentinH** [comment]
Indeed you're right. Thanks ;)
