### ISSUE TITLE
Slider with ticks not working on ie9/10

### ISSUE THREAD

**Issue by ciriac** [rzajac/angularjs-slider#160]
The ticks are not working on IE9/10 because there's no support for display flex. Has anyone encountered this issue before?

**Comment by ValentinH** [comment]
Damn IE! I thought it was OK at least on IE10... Previously I was using a table display but in order to display the ticks values, flexbox was the simplest way I found.

**Comment by ValentinH** [comment]
There seems to be a solution for IE10 by using vendor specific prefixes. I'll try to add them.

**Comment by ciriac** [comment]
Thanks. Can confirm that adding the vendor prefixes resolves the issue on IE10.

**Comment by ValentinH** [comment]
Actually in IE11 emulating IE10, ticks are displayed correctly. Are you sure they are wrong in IE10? However, there are totally messed up when emulating IE9...

**Comment by ValentinH** [comment]
OK, can you add a pull request with these prefixes because I can't test them since I don't have a real IE10.

**Comment by ValentinH** [comment]
Good resource about increasing the browsers support for flexbox: https://css-tricks.com/using-flexbox/

**Comment by ciriac** [comment]
I don't have access to a real IE10 either. I'm currently using browserstack to test IE9/10. I just went through that page on css-tricks earlier, but ended up using bourbon (http://bourbon.io/docs/#flexbox) since it's already in my project.
