### ISSUE TITLE
Does not calculate width when element is hidden using ng-show on ng-include

### ISSUE THREAD

**Issue by aghos7** [rzajac/angularjs-slider#164]
We have a ng-include where the src has a slider in it.  The ng-include also uses ng-show to determine if the ng-include should be visible.  When the app first starts, the ng-show evaluates to false and thus the slider is not shown.  When the ng-show transitions to a true value, the slider is displayed at the minimum value when the model value is not the minimum value.  Changing the ng-show to an ng-if resolves the issue, but the bounds of the slider should probably be recalculated when visibility changes.

Example:
main.html:
```<ng-include src="file-with-slider.html" ng-if="file-with-slider.visible()"></ng-include>```
file-with-slider.html:
```
<rzslider
  rz-slider-floor="file-with-slider.MIN_VOLUME"
  rz-slider-ceil="file-with-slider.MAX_VOLUME"
  rz-slider-always-show-bar="true"
  rz-slider-model="file-with-slider.sliderValue"
  rz-slider-hide-limit-labels="true"></rzslider>
```

**Comment by ValentinH** [comment]
This is a known problem: the slider can't know when its parent becomes visible. You need to send an event to force it to redraw when you set your ng-show to true.
```js
vm.refreshSlider = function () {
    $timeout(function () {
        $scope.$broadcast('rzSliderForceRender');
    });
};
```
Here's a pretty similar example using bootstrap tabs: http://jsfiddle.net/7w755fLv/

Also, in the next version (see in the PRs), there will be an example with ng-show: https://jsfiddle.net/kur7d101/light/
