### ISSUE TITLE
bubble and label overlaps

### ISSUE THREAD

**Issue by mpaluszkiewicz** [rzajac/angularjs-slider#166]
When min and max are the same, bubble label and tick label are overlapping each other.

See:
![bug](https://cloud.githubusercontent.com/assets/2063392/10921031/951ea880-8273-11e5-9fe4-f07fd82f06bc.PNG)

**Comment by mpaluszkiewicz** [comment]
And I don't know why but attributes rz-slider-show-ticks and rz-slider-show-ticks-value do not work. I'am using version 1.0.0

**Comment by ValentinH** [comment]
Could you please provide a JSFiddle showing the issue please? You can fork the one in the ReadMe

**Comment by mpaluszkiewicz** [comment]
Indeed, it is fixed in master but not in latest tag (1.0.0). When you will create now tag? I don't like using 'master' or 'latest' version in bower.

**Comment by mpaluszkiewicz** [comment]
Ok, everything is clear now. Version `1.0.0` is not latest but `0.1.36` is. Weird :)

**Comment by ValentinH** [comment]
Are you using a package manager? Indeed, I haven't released a version since this fix so its only on master. I'll bump a new version later today.

**Comment by ValentinH** [comment]
I released v1.1.0 should be OK now.
