### ISSUE TITLE
Angular getter-setter support

### ISSUE THREAD

**Issue by agray** [rzajac/angularjs-slider#169]
FEATURE REQUEST: It would great if Angular getter-setter support could be added as an enhancement

**Comment by ValentinH** [comment]
Could explain what are getter-setter in Angular?

**Comment by agray** [comment]
Docco about getter setters is on this page https://docs.angularjs.org/api/ng/directive/ngModel

**Comment by ValentinH** [comment]
But we are not using ng-model in this directive...

**Comment by agray** [comment]
Are not the directive attributes bindable to variables that exist on the Angular model?

<rzslider
    rz-slider-floor="priceSlider.floor"
    rz-slider-ceil="priceSlider.ceil"
    rz-slider-model="priceSlider.min"
    rz-slider-high="priceSlider.max"
    rz-slider-translate="translate"
    rz-slider-on-change="onSliderChange()"
    rz-slider-show-ticks="true"></rzslider>

**Comment by ValentinH** [comment]
I'm very sorry but I still don't understand what you want...
