### ISSUE TITLE
Slider intilzation callback 

### ISSUE THREAD

**Issue by CharnjeetIotasol** [rzajac/angularjs-slider#171]
Can you please provide me intilzation callback event

**Comment by ValentinH** [comment]
What do you mean?

**Comment by CharnjeetIotasol** [comment]
I want to perform some action when slider is fully intilzation.

**Comment by ValentinH** [comment]
Hmm, I don't really the idea of adding such a specific feature to the library... What's your use-case?

**Comment by ValentinH** [comment]
Closing as no answer for a month.
