### ISSUE TITLE
upper handle of draggable range jumps to strange places if minValue is not 0

### ISSUE THREAD

**Issue by ursgrob** [rzajac/angularjs-slider#172]
I created a fiddler demo:

https://jsfiddle.net/rzupvdfs/

move the range compeltely to the left. The high handle will jump to the left for about the same value as defined as floor.

The fix would be in rzslider.js in "onDragMove":

The first if block should look like this:

      if (newOffset <= this.dragging.lowDist)
      {
        if (pointer.rzsl === this.dragging.lowDist) { return; }
        newMinValue = this.minValue;
        newMinOffset = 0;
        newMaxValue = this.minValue + this.dragging.difference; // <-- add minValue
        newMaxOffset = this.valueToOffset(newMaxValue);
      }

Great slider btw :)

**Comment by ValentinH** [comment]
Indeed, you are right. I'll fix it once the 2.0.0 version is released (soon). You can see it in the PR list if you want.

**Comment by ValentinH** [comment]
Fixed in master.
