### ISSUE TITLE
Different colors for selection bar based on model value

### ISSUE THREAD

**Issue by ValentinH** [rzajac/angularjs-slider#173]
[Added for @termita81]
Changing color for the selected part, so that for instance at 20% it's green and at 80% it's red

**Comment by lookfirst** [comment]
Gah! I totally need this... I guess it is off to the software mines...

**Comment by ValentinH** [comment]
I think this could indeed be a good feature but I have no idea what do implementation should be... 
Passing an array of colors that would evenly be spread on the slider, a more complex structure describing the colors or the slider would simply set a unique CSS class for each value.

**Comment by termita81** [comment]
The way I hacked it in my project was to just pass a function name in some attribute, and call that whenever the slider value is changed.

**Comment by ValentinH** [comment]
Indeed, this would unload the library from this logic. So the function would return the current color?

**Comment by termita81** [comment]
Yes, I think that would be the most flexible approach.

**Comment by ValentinH** [comment]
The PR has been merged.

**Comment by lookfirst** [comment]
@ValentinH :+1: how about a release now? ;-)

**Comment by ValentinH** [comment]
I would prefer to close the 2 others PRs to do a bigger release. Do you really need a release?

**Comment by lookfirst** [comment]
I need a release in order to grab your code cause I use jspm for my packaging...

**Comment by lookfirst** [comment]
I could go with master, but that is a bit dangerous. ;-)

**Comment by ValentinH** [comment]
OK I'm doing it now.

**Comment by ValentinH** [comment]
It's done.

**Comment by lookfirst** [comment]
@ValentinH I just integrated this into my site... just wanted to follow up and say thanks for your great work! =)

**Comment by ValentinH** [comment]
I'm glad it's useful to you. ;)
