### ISSUE TITLE
when using stepsArray you cannot use the translate function

### ISSUE THREAD

**Issue by kevohagan** [rzajac/angularjs-slider#177]
this can be seen here: https://github.com/rzajac/angularjs-slider/blob/master/src/rzslider.js#L368

shouldnt this be an improvement? 

:)

**Comment by ValentinH** [comment]
Indeed, I couln't find a use case where I needed both stepsArray and translate. I discussed it in #163 .

StepsArray values should already be translated. 

If you have a use case in mind that need both features, please share it. :)

**Comment by kevohagan** [comment]
Well i guess its quite obvious, same use case as using translate in the first place.

for example a list of of numerical values that i want to display with a currency symbol. I dont think the steparray values should already have that currency symbol no?

maybe im missing something

**Comment by ValentinH** [comment]
I'm actually using the stepsArray to display money and I directly add the symbol in the stepsArray values. It is more efficient since you don't need to recompute them at runtime.

**Comment by ValentinH** [comment]
In my opinion, a translate function would be necessary if the steps values change while the slider is dragged. Otherwise, you only need to update the stepsArray.

For the currency example, I would do:
```js
vm.values = [1, 10, 100, 1000];
vm.sliderConfig = {
  stepsArray: vm.values.map(function(v) {
                       return '$' + v;
                    })
};
}
```

**Comment by ValentinH** [comment]
Closing as no answer for more than a week
