### ISSUE TITLE
Slider not working on mobile view on pre kitkat devices

### ISSUE THREAD

**Issue by madhur** [rzajac/angularjs-slider#178]
Due to some issue slider is not rendered correctly on Android Webview pre kit-kat. Here is an example here:

http://www.madhur.co.in/jobform/

Try opening on an Android webview. It renders very small.

**Comment by ValentinH** [comment]
I don't have a pre kit-kat device to test it so I can't really tell you what's the problem... Could you provide a screenshot?

**Comment by madhur** [comment]
It was a ionic issue. More info here:

http://stackoverflow.com/questions/33787026/page-renders-incorrectly-on-pre-kitkat-device-webview
