### ISSUE TITLE
Initial Value Not Being Set

### ISSUE THREAD

**Issue by TikiMotel** [rzajac/angularjs-slider#179]
I have an rzSlider with some range N..M and an initial value X. When the slider first renders, the value X is correctly displayed above the thumb/pointer. However, the thumb is displayed at the far left (when X is in the middle of N..M), and the endpoint values are not displayed. As soon as I drag the thumb, then the endpoints are displayed, and the thumb position is correct. Also, setting the value via the $scope does not work initially, but does once you have dragged the thumb at least once. And broadcasting 'rzSliderForceRender' has no effect. What am I doing wrong? Thanks in advance!

**Comment by ValentinH** [comment]
You should try broadcasting therzSliderForceRender message inside a $timeout call. This is certainly a timing issue.

**Comment by TikiMotel** [comment]
OK, figured it out. I have the slider in a tabset. If the slider value is set when that tab is not selected/visible, the slider will not update. Broadcasting 'rzSliderForceRender' when the tab becomes selected resolves the issue. By the way, I've tried five different angular sliders, and this one is by the best!

**Comment by ValentinH** [comment]
Actually there is an example of sliders inside tabs on the example page.

**Comment by TikiMotel** [comment]
Ya, I see that now, missed it before. Incidentally, it works fine if I broadcast the event on ng-click of the tab, don't even need the $timeout. Thanks!

**Comment by ValentinH** [comment]
If you use the ui-bootstrap tabs, there is even a special callback `select` called when tab is activated.
