### ISSUE TITLE
include CSS reference in index.html

### ISSUE THREAD

**Issue by bennettatoms** [rzajac/angularjs-slider#180]
Not an issue with the code, but the README omits any mention of including the CSS references in index.html. I spent a couple hours trying to figure out why, after including the 'rzModule' dependency in my app module and the rzslider.js script file reference in index.html per the Project Integration instructions, the sliders were not actually showing up in browser. Turns out all it was was the missing link to the CSS file. Excellent work, though, thanks!

**Comment by ValentinH** [comment]
Indeed, thanks for reporting.
