### ISSUE TITLE
stepsArray doesn't load properly with range slider

### ISSUE THREAD

**Issue by ryanrk** [rzajac/angularjs-slider#181]
The max value seems to be undefined unless you move it. 

https://jsfiddle.net/170bymjp/

**Comment by ValentinH** [comment]
You are using it the wrong way. When using stepsArray, the min and max values are the indexes of the array. You don't need to set the floor and ceil options, they are handled automatically. 

Here's a working version: https://jsfiddle.net/4zrr2y55/

BTW stepsArray is here to display non linear values. If you want to display 10, 20, 30 then just set floor=10, ceil=30 and step=10.

**Comment by ryanrk** [comment]
Ah, the index's makes sense.  Yes, i'm using non linear values.  10,20,30 was a bad example.
