### ISSUE TITLE
Please can you add a property to bound labels to within the slider

### ISSUE THREAD

**Issue by zebslc** [rzajac/angularjs-slider#182]
If using bootstrap columns, it is really easy to make the slider translated label appear over the form label or off the edge of the page with anything more than the single percentage labels used in your example.

Please can you add a configuration property that bounds any translated labels within the left and right of the slider (probably default off for performance)

https://jsfiddle.net/jbaggaley/d356L6rL/5/

![mobile width](https://cloud.githubusercontent.com/assets/3459059/11339766/ed35f616-91f2-11e5-80fa-4077231b6fc5.PNG)
![label overwrite](https://cloud.githubusercontent.com/assets/3459059/11339770/f08c936a-91f2-11e5-923f-c6e1eafcf433.PNG)

Thank you  :-)

**Comment by ValentinH** [comment]
I totally agree and I don't think it should be with an attribute: labels should be inside the slider bounds.

There is the #135  PR that tries to do it, but there is still a few bugs...

**Comment by zebslc** [comment]
cool - sorry I didn't notice this!  Feel free to use fiddle as part of test..


Thank you! :smile:

**Comment by ValentinH** [comment]
Actually the PR was ready but needed rebasing. Since I had no news from its author, I added his code myself to master.
