### ISSUE TITLE
onEnd not fired on range slider ?

### ISSUE THREAD

**Issue by asso1985** [rzajac/angularjs-slider#183]
Seems like onEnd is not fired on range slider

**Comment by ValentinH** [comment]
Do you mean the event broadcasted on scope or the callback function?

**Comment by asso1985** [comment]
The callback function

**Comment by ValentinH** [comment]
Can you provide a JSFiddle showing the issue please?

**Comment by asso1985** [comment]
I've updatetd the module with bower and now is working, sorry. I'm closing.
