### ISSUE TITLE
Range slider with multiple values?

### ISSUE THREAD

**Issue by prasadrails** [rzajac/angularjs-slider#186]
Hi, 
Is it possible Range slider with multiple values ? 
My requirement is like divide 100% into multiple parts.
Example: 
RGB colors, user can using our slider set Red-20%, Green-30%, Blue-50%(balance)
Finance share amount between people.
http://www.bacubacu.com/colresizable/#samples in that multiple range slider 
http://stackoverflow.com/questions/10485075/slider-with-multiple-handle-and-background-color-for-content

Can you suggest any one how to achieve using this or new slider ?
Thanks,
Prasad.

**Comment by ValentinH** [comment]
Hello,

Unfortunately, this is not possible currently. The only way to achieve something similar would be to display 3 sliders next to each others and synchronize them manually using the onChange callback.

**Comment by ValentinH** [comment]
Here's a quick and dirty example of what I mentioned above: http://jsfiddle.net/cp26dk2g/

**Comment by prasadrails** [comment]
Thanks ValentinH for very quick response.

**Comment by ram-legion** [comment]
Please include this feature for having 
1) multiple colored slider bar  
2) mutliple handles to control the range.
3)ticks on custom position(as markers)

**Comment by ValentinH** [comment]
Sure I'll do this right now!
