### ISSUE TITLE
floor and ceil change from controller 

### ISSUE THREAD

**Issue by hossam9995** [rzajac/angularjs-slider#187]
hello 

my issue is my floor and ceil  , its  not change when i receive data from back end and i want to accept it to my  range slider , the min and max value is change without any problem, but the floor and ceil its still the same after i change it in the controller ?! is there any solution

thx

**Comment by ValentinH** [comment]
Could you please provide a JSFiddle showing the issue? Its not very clear to me right now.

**Comment by hossam9995** [comment]
ohh its work fine here
https://jsfiddle.net/nayef/oymysoyu/

my issue with $scope and $rootscope ,

thx for fast replay
