### ISSUE TITLE
rz-slider-on-end not working

### ISSUE THREAD

**Issue by aircable** [rzajac/angularjs-slider#188]
I need to identify which slider created the callback. Every attempt to do that is not working. Even the id is not passed into any callback mechanism. The onEnd option function does not pass parameter either. The injected event only passes $scope.
And this option does not even create a callback: rz-slider-on-end="onSliderEnd( parameter)".
Any idea how to implement this?

<div ng-repeat="device in devices">
   <rzslider rz-slider-model="device.data[2]"
       rz-slider-on-end="onSliderEnd( device )">
   </rzslider>
</div>

**Comment by ValentinH** [comment]
What version are you using? Since version 2, there is no `rz-slider-on-end` attribute but there is a`rz-slider-options` that takes an object...

**Comment by aircable** [comment]
I have tried that and I can't make it work. I cannot figure out which
slider it was.

The combination of ng-repeat and your slider that does not identify itself
which object it controls is not possible.
onEnd does not provide parameter.
Since then I, using material slider <md-slider,,, That works like this:

<md-slider flex min="0" max="100" ng-model="device.data[2]"
aria-label="blue" id="device.source" ng-mouseup="light( device )"
class="md-primary">
</md-slider>

See, I need the object "device" to identify which slider it was. The number
of sliders is dynamic on the screen.

Thanks for your help anyway.

You may want to update the various old pages that describe the use of the
rz-slider-on-end
And the version you have on Github, the version you get with npm and the
version for bower differ.

Cheers
Juergen

On Sun, Nov 29, 2015 at 10:12 PM, Valentin Hervieu <notifications@github.com

**Comment by ValentinH** [comment]
The latest version on github, npm and bower is 2.1.0. 

I have tried to make the documentation in the ReadMe as clear as possible but if there are still some unclear points, let me know and I'll update it.

If you can provide a JSFIddle showing your issue, I could help you but with the info you gave me, I can't do anything.

**Comment by fredrickJones** [comment]
I am having the same issue and here is a fiddle that I hope shows what is happening.

http://jsfiddle.net/j141ved2/3/

**Comment by ValentinH** [comment]
@fredrickJones I don't see what the issue is apart from the fact that `setContrast` is not defined.

**Comment by fredrickJones** [comment]
I know setContrast isn't defined, I know what I wnat to do in the function when I get the object to it. I am not sure how to reference that specific iteration of the ng-repeat in my function. I don't see how I can send through an an argument from the front-end ie: setContrast(img).
Everything that I have seen sends a sliderId, modelValue, highValue but I need the whole img object.

**Comment by ValentinH** [comment]
I don't see any update on your fiddle...

**Comment by fredrickJones** [comment]
I defined the function at the bottom plus added some comments.

http://jsfiddle.net/j141ved2/6/

**Comment by ValentinH** [comment]
You should use the id option in order from which slider your `onEnd` is called like on this example: http://jsfiddle.net/7m0aoLcf/ . Then you should be abel to retrieve to correct img from the id.

**Comment by fredrickJones** [comment]
so there is no way to bring in the whole object, just a reverence to the id?

**Comment by ValentinH** [comment]
What object are you talking about?

**Comment by fredrickJones** [comment]
never mind I think I just figured it out. I was didn't see everything that you had done on the fiddle.

**Comment by ValentinH** [comment]
You are welcome! ;)
