### ISSUE TITLE
limits are in wrong position 

### ISSUE THREAD

**Issue by samirchian** [rzajac/angularjs-slider#189]
when the page loaded limit numbers are in wrong position. 
![image](https://cloud.githubusercontent.com/assets/7979308/11577667/5c5f3442-99d4-11e5-95b7-afe287ffbd3d.png)

**Comment by ValentinH** [comment]
If when you change the value of the slider, they all get positioned correctly, then see #164. Otherwise, can you reproduce it in a JSFiddle example so I can have a look?

**Comment by samirchian** [comment]
yes after change it fixed. and #164 fixed it. Thanks
