### ISSUE TITLE
Support floating point numbers

### ISSUE THREAD

**Issue by goldenram** [rzajac/angularjs-slider#190]
This is a great slider implementation, just need support added for floating point numbers and decimal precision.  Use case would be the ability to set the min, max and values to numbers like -2.056 or 3.1.
Also it would be good when implementing this to allow one to specify the number of decimal places to show, for example show 2.1 or 2.109.

**Comment by ValentinH** [comment]
This is already possible using the step and precision options! ;)
There you go: http://jsfiddle.net/mhc4cx0h/ .

**Comment by goldenram** [comment]
Sorry, it appears to sometime work, using the demo page I see this, which is why I thought it was not supported.  I see NaN when setting the step to .1 and precision to 3.

![slidernan](https://cloud.githubusercontent.com/assets/16142020/11594895/89aaaa84-9a7a-11e5-9c15-0a15b5f75bc2.PNG)

**Comment by ValentinH** [comment]
Indeed, changing it in the all options demo can lead to weird behaviour. This might not be the best example ever! :D Step and precision must always have compatible values in order to have a working slider.

**Comment by goldenram** [comment]
Ah, ok, so the key is getting the step and precision compatible.  Do you have a range example handy? I must keep running into the step and precision issues.

**Comment by ValentinH** [comment]
Sure, there you go: http://jsfiddle.net/gnp572dv/ .

**Comment by goldenram** [comment]
Thanks Valentin!  I do notice that if the numbers are less than 0 they are rendered incorrectly.
For example:

    minValue: -2.002,
    maxValue: -1.002,
    options: {
      floor: -5.000,
      ceil: -1.000,
      step: 0.001,
      precision: 3
}

Those numbers render off by .001 in the fiddler.  Can you confirm? or did I set something up wrong?

**Comment by ValentinH** [comment]
Indeed, there is a bug. Can you fill an issue please? I'll have a look tomorrow.
Demo: http://jsfiddle.net/7bbf78op/
