### ISSUE TITLE
How do handle slider inside the ng-repeat with undefined or null values?

### ISSUE THREAD

**Issue by Karthik9836** [rzajac/angularjs-slider#194]
Hi

I am a beginner in AngularJS and trying to implement the Range slider for a scenario in my application and I am facing the following scenario shown in the below fiddle.
http://jsfiddle.net/Karthik9836/ed7cvfwc/

The API response returned as a _collection_, would give me the all the **MIN, MAX, FLOOR, CEIL** values for each and every range slider. How do I handle scenarios where the API response for **MIN, FLOOR** values returned from API as either _**undefined or null cases**_. I can't change the API response, I need to handle at the my UI end.

Thanks in advance.

**Comment by ValentinH** [comment]
Undefined and null values are invalid for this slider, you need to sanitize the values before remdering them as sliders. 

The library set default values to floor and ceil when they are null: floor is set to 0 and ceil is set to the max value between model and high attributes.

**Comment by Karthik9836** [comment]
Okay. Thank you for the quick response. Let me sanitize my response.
