### ISSUE TITLE
how to pass parameter on SlideEnded

### ISSUE THREAD

**Issue by secabhi** [rzajac/angularjs-slider#195]
Hi I have 3 slider i want to call SlideEnded and pass params to identify which slider got called . i have tried rz-slider-on-change but its is not working
http://jsfiddle.net/vqep92wo/1/

**Comment by ValentinH** [comment]
Are you using version 1.X.X or 2.X.X?

**Comment by secabhi** [comment]
2.X.X

**Comment by ValentinH** [comment]
Then there is no ceil, floor or onChange attributes anymore, everything should be in the options object.

**Comment by secabhi** [comment]
can one do one help if i am using 3 slider how i can pass parameter on 
$scope.$on('slideEnded', function (val) {
//val is my slider name which i am using
}

**Comment by ValentinH** [comment]
So are you using version 1 or 2?

**Comment by secabhi** [comment]
i am using 1 version

**Comment by ValentinH** [comment]
Then use version 2! :D 

I'm kidding but you started by saying that you used version 2.X.X.... It wasn't possible to do this with version 1 I think.
