### ISSUE TITLE
how to fire an event when slider value change and call a function 

### ISSUE THREAD

**Issue by himanshugoyal5734** [rzajac/angularjs-slider#198]
i do't understand how i can fire the an function when a slider value change

**Comment by ValentinH** [comment]
You need to register a function on the onChange option using the rzSliderOptions attribute.
Example: http://jsfiddle.net/uz9eLpar/ .

**Comment by himanshugoyal5734** [comment]
this example is wonderful but my range slider is double and after doing this i can't able to fire an function.. is you have any example of double range slider for fire an function when release the click on button

**Comment by ValentinH** [comment]
Like this: http://jsfiddle.net/muwetwLc/ ?

**Comment by himanshugoyal5734** [comment]
yes thanks sir i try this...

**Comment by himanshugoyal5734** [comment]
$scope.minRangeSlider = {
        minValue: 0,
        maxValue: 10000,
        options: {
            floor: 0,
            ceil: 10000,
            step: 1,
            onEnd: $scope.searchByPrice(0)
        }
    };


<rzslider rz-slider-model="minRangeSlider.minValue" rz-slider-high="minRangeSlider.maxValue" rz-slider-options="minRangeSlider.options" ></rzslider>



is this code right ?? function is not fire

**Comment by ValentinH** [comment]
Nope it is wrong.

The problem is with the way you set the onEnd function. Now, `onEnd` is not set to a function but to the result of `searchByPrice`.

So you can do:
```js
$scope.minRangeSlider = {
        minValue: 0,
        maxValue: 10000,
        options: {
            floor: 0,
            ceil: 10000,
            step: 1,
            onEnd: $scope.searchByPrice
        }
};
```
If the way above, you need your `searchByPrice` to be declared before this code.

But if you really need to pass 0 to your searchByPrice, then do:
```js
$scope.minRangeSlider = {
        minValue: 0,
        maxValue: 10000,
        options: {
            floor: 0,
            ceil: 10000,
            step: 1,
            onEnd: function() {
                 $scope.searchByPrice(0);
            }
        }
};
```
With the code above, you can declare `searchByPrice` wherever you want.

**Comment by himanshugoyal5734** [comment]
thanks sir .. it solve my problem and working correctly....

**Comment by himanshugoyal5734** [comment]
sir you have any date range picker for getting the two dates and perform a operation???

**Comment by ValentinH** [comment]
Please use https://gitter.im/rzajac/angularjs-slider to chat ;)
