### ISSUE TITLE
Is it possible to lock range?

### ISSUE THREAD

**Issue by yelnar** [rzajac/angularjs-slider#199]
Whenever I change the range its length would stay the same. This would be awesome.

**Comment by ValentinH** [comment]
Is this similar as #196 ?

**Comment by yelnar** [comment]
Yes it is. Now I use `onEnd` option to implement it, but it is little bit dirty so I think it would be awesome to have this feature natively.

**Comment by ValentinH** [comment]
It should not be very hard to implement it. It's the next thing on my todo list ;) 

I'm closing this one as duplicate of #196 .
