### ISSUE TITLE
unlink model and high values

### ISSUE THREAD

**Issue by Mencls** [rzajac/angularjs-slider#200]
Hi Valentin, I was wondering if it was possible to have two free/unlinked models on the slider. 
A simple example:
    rz-slider-model="targets.value1"
    rz-slider-high="targets.value2"

For now , if you move the rz-slider-high pointer and it becomes smaller than the rz-slider-model value, then the slide will update value1 and not value2 anymore.

Can we avoid this ? I have two different models I'd like to update on one slider, and the smallest/highest thing doesn't really matter.

Merci, Clément.

**Comment by ValentinH** [comment]
Nope this is not possible.

Basically, you want to display 2 values on the same slider but it doesn't represent a range, isn't it?

**Comment by Mencls** [comment]
Exactly

**Comment by ValentinH** [comment]
OK I've tried to find a workaround with the current version but without success.
I'm sorry, but the concept of always having `rzScopeModel <= rzScopeHigh` is used in many places of the library internal logic so it would require a lot of changes...
It is defintively possible but I think it would bring too many specific changes for this issue.

It could be a good opportunity to create a fork (that could be merged later if it brings enough new stuffs) that could handle an unlimited number of handles...

**Comment by Mencls** [comment]
Yes this is what I thought too. Thank your for your answer!
