### ISSUE TITLE
onChange Fires for All Sliders, and Multiple Times

### ISSUE THREAD

**Issue by queejie** [rzajac/angularjs-slider#202]
Hi, thanks for creating this slider!  

I have a fork of your example here: http://jsfiddle.net/davidquinnjacobs/ashs3bad that demonstrates that when one slider is changed, the onChange fires for all sliders.  You have to look at the console to see the firing messages.  Also, it seems to fire many times on startup and twice on every click to a new value.

Is there anything I can do to avoid this, or is this an issue in the slider?

Thank you,
-dqj

**Comment by ValentinH** [comment]
Indeed, you are using it the wrong way. Here's a valid solution: http://jsfiddle.net/pa9dgu6g/ . Although I wouldn't directly define the options in the template...

Your mistake is pretty much the same than #198 .

**Comment by queejie** [comment]
Thank you!  I was using the ventura rocket slider, but that is looking inactive now.  One thing it had that was nice was being able to pass in arguments to the onChange function.   Maybe something for down the road?

**Comment by ValentinH** [comment]
What argument so you want to pass? Can you show an example with Ventura?

To pass custom argument, you can wrap your function with an anonymous one like I showed in #198
