### ISSUE TITLE
Version 0.1.6 does not update when dragging the slider, 0.1.5 does.

### ISSUE THREAD

**Issue by bgrawi** [rzajac/angularjs-slider#21]
I can reproduce this on the latest versions of Firefox and Chrome. 0.1.6 simply won't update the model when touching/dragging the mouse, while 0.1.5 will work. I am not including jQuery in the project, it is all just angularjs with jqLite.

If it means anything, I am also using a touchscreen monitor which way or way not be a factor.

**Comment by stpangia** [comment]
I also could not get 0.1.6 to work. Perhaps it should be moved into a development branch and the distribution rolled back to 0.1.5?

**Comment by rzajac** [comment]
Fixed in latest release and master
