### ISSUE TITLE
CSS not applied when rzslider is attribute

### ISSUE THREAD

**Issue by zewt112** [rzajac/angularjs-slider#23]
The CSS is written apply to an element called 'rzslider'. The directive allows the user of rzslider as an attribute with the "restrict: 'EA'" property. However, using the slider as an attribute to, say, a div, sees the CSS styles not applied, so the slider is not visible.

**Comment by rzajac** [comment]
This is actually oversight. Slider should be restricted only to elements.

**Comment by thomasfrantz** [comment]
Actually, you can make it work : 
Add an attribute class rzslider to the div with rzslider attribute and copy/paste (or change directly) the css, adding "." to every "rzslider" like this : 
.rzslider span.rz-bubble.rz-limit {
  color: #55637d;
}
It works fine for me :)
