### ISSUE TITLE
add selection bar when slider have only one pointer

### ISSUE THREAD

**Issue by corcisun** [rzajac/angularjs-slider#26]
Now the selection bar "<span class="bar selection"></span>" is rendered only when I define two pointers, such as the first example in your plunker (http://embed.plnkr.co/53AUdB/preview). 
 
It's better if the selection bar appears when I want, also when i use only one pointer..
You could set the selection bar in slider only by configuration or whatever you want.

If you make this issue you make me happy :) 

thanks.

PS: I can't send a screenshot of what I am thinking because github have some problem with uploads. I will upload an image as soon as i can.

**Comment by psalaberria002** [comment]
+1
