### ISSUE TITLE
Slider display vertical

### ISSUE THREAD

**Issue by georgecampos** [rzajac/angularjs-slider#31]
Hi, Great job on this slider! I have an application where it's important for the slider to display vertically rather than horizontally. Is this possible? If so how would I do it?

Thanks, I really appreciate the simplicity and elegance and 'no dependencies' in your code.

**Comment by rzajac** [comment]
This should not be very hard I think but I have no plans to add it at the moment. I would gladly take pool request though :)

**Comment by dshep4** [comment]
I'll be working on it, let you know how it goes
