### ISSUE TITLE
"Filter" the limits and current value?

### ISSUE THREAD

**Issue by magicwrites** [rzajac/angularjs-slider#39]
Hello.

If you accept feature requests, I think the slider would benefit from a way to supply some kind of a filter option. I would like to parse the maximum and minimum limit values with standard angular "number" filter, and I am unable to do so, rendering slider inconsistent with all of my project's number values.

Transiterate has a nice way of doing so, if an example helps: http://witq.github.io/ng-transiterate/#/usage

Otherwise quite well done slider, certainly best I found so far. Good job.

Cheers,
Maciek

**Comment by rzajac** [comment]
I believe this is exactly what rz-slider-translate is doing.
