### ISSUE TITLE
Slider with dualknobs wont initialize correctly

### ISSUE THREAD

**Issue by dannystyleart** [rzajac/angularjs-slider#42]
Hello guys!

I'm using the slider with dualknobs - as a range slider - and I'm applying the model and the high value but the slider wont initialize correctly. Both knobs are on the zero value.

Currently I'm using the 0.1.5 version - via angular 3.1.14 - because of 0.1.6 buggy and can't drag the knobs.

**Comment by dannystyleart** [comment]
Now, I have inspected the source of the problem is the display:none of the container element, it reflects to all the children.

Currently I'm trying to use this directive in the (angular) bootstrap-ui-s tabset.

**Comment by mmmeff** [comment]
Seeing a similar problem by putting the slider in a custom popout. It's kind of an itegration issue - we need to find a way to avoid initializing the module until it's displayed.

**Comment by rzajac** [comment]
Using slider events https://github.com/rzajac/angularjs-slider#slider-events should solve your issues

**Comment by BobbieBarker** [comment]
Could you be a bit more explicit about how one would use the slider events to resolve the issue?

**Comment by psalaberria002** [comment]
You could broadcast the "rzSliderForceRender" event in order to re-render the slider.

This example calls the event after a modal is rendered:

    modalInstance.rendered.then(function(){
                $rootScope.$broadcast('rzSliderForceRender');//Force refresh sliders on render. Otherwise     bullets are aligned at left side.
            });

See full example here: https://github.com/rzajac/angularjs-slider/blob/gh-pages/index.html

**Comment by dannystyleart** [comment]
Thanks for reply. Its true, that this solution triggers the rerendering of the slider and altough we have custom display component ( Like aside in angular-strap ) we have still issues with sliders in fluid containers. - And yeah we are using the re-render-event-firing solution.
The problem is:
In initial state the dualknob sliders' maximum value knob always have been rendered out of the view somehow. Even if no the knob will be renderet close to the max value point but not on it. 
After user clicks on the slider both knobs will fix their position.

We are using bootstrap css framework and a bit of ui-bootstrap components but I don't see if there would be any conflict since we are using the .min version of all 3rd party component.

**Comment by ValentinH** [comment]
Could you provide a minimal example showing your issue? You can fork this http://jsfiddle.net/pq7yr6d6/

**Comment by dannystyleart** [comment]
I have figured out that the problem was occured only when the sliders were placed in ui-tabs.
my fix was about to broadcast the forceRender event on ui-tabs' select event.
I think this is a unique problem since I was tried other tab direcives, also wrote one just for cause and none of others produced this bug.

Thanks for help, we can now close this issue I think :)
