### ISSUE TITLE
Ability to pass the template as a string or a templateUrl for the slider

### ISSUE THREAD

**Issue by psalaberria002** [rzajac/angularjs-slider#49]
It would be great to be able to edit the template for the slider. Maybe an attribute in the directive? What do you think?

**Comment by psalaberria002** [comment]
What about something like this? I need to change the html inside the pointer, and this solves the issue.

Any other idea?

Thank you.

.directive('rzslider', ['$compile','RzSlider', function($compile,Slider)
{
  return {
    restrict: 'E',
    scope: {
      rzSliderFloor: '=?',
      rzSliderCeil: '=?',
      rzSliderStep: '@',
      rzSliderPrecision: '@',
      rzSliderModel: '=?',
      rzSliderHigh: '=?',
      rzSliderTranslate: '&',
      rzSliderHideLimitLabels: '=?',
      rzSliderAlwaysShowBar: '=?',
      rzSliderTemplate: '=?'
    },

    link: function(scope, elem, attr)
    {
        var template ='<span class="rz-bar"></span>' + // 0 The slider bar
                    '<span class="rz-bar rz-selection"></span>' + // 1 Highlight between two handles
                    '<span class="rz-pointer"></span>' + // 2 Left slider handle
                    '<span class="rz-pointer"></span>' + // 3 Right slider handle
                    '<span class="rz-bubble rz-limit"></span>' + // 4 Floor label
                    '<span class="rz-bubble rz-limit"></span>' + // 5 Ceiling label
                    '<span class="rz-bubble"></span>' + // 6 Label above left slider handle
                    '<span class="rz-bubble"></span>' + // 7 Label above right slider handle
                    '<span class="rz-bubble"></span>'; // 8 Range label when the slider handles are close ex. 15 - 17
                    
        if(scope.rzSliderTemplate !== undefined){
            template=scope.rzSliderTemplate;
        }
        elem.html(template);
        $compile(elem.contents())(scope);

        return new Slider(scope, elem, attr);
    }
  };
}]);

**Comment by rzajac** [comment]
I would rather go somewhere in this direction: http://stackoverflow.com/a/20659860/282882

**Comment by rzajac** [comment]
Implemented by #51
