### ISSUE TITLE
Error with min file

### ISSUE THREAD

**Issue by oliviercpl** [rzajac/angularjs-slider#59]
Hello,

i have the following error with version v0.1.16 with the file /angularjs-slider/dist/rzslider.min.js:
Uncaught Error: [$injector:unpr] Unknown provider: aProvider <- a

It work fine with the file /angularjs-slider/rzslider.js

**Comment by xingped** [comment]
I've created a pull request for this fix.

**Comment by psalaberria002** [comment]
I had just created exactly the same fix ;)

**Comment by xingped** [comment]
I just noticed that too.  :(  You beat me by 2 minutes!

**Comment by rzajac** [comment]
Fixed
