### ISSUE TITLE
Sliders with decimal step broken

### ISSUE THREAD

**Issue by ValentinH** [rzajac/angularjs-slider#62]
The 9fa6c4a1500d commit broke specific sliders were values are decimal.

For instance, the following slider doesn't work anymore and only display Integer values:
```html
<rzslider class="slider" rz-slider-floor="0.5" rz-slider-ceil="1.5" rz-slider-step="0.1"
              rz-slider-precision="1" rz-slider-model="slider_data"></rzslider>
```

**Comment by carenzi** [comment]
decimal steps seems to be broken again?

**Comment by ValentinH** [comment]
Nope: http://jsfiddle.net/h8hm6365/

**Comment by carenzi** [comment]
Awesome.  thanks.  I was missing rz-slider-precision="1"

**Comment by ValentinH** [comment]
You are welcome ;)

**Comment by Hesesses** [comment]
Seems to be broken? 
http://jsfiddle.net/h8hm6365/30/

**Comment by ValentinH** [comment]
Yes because it was using the old API. Here is the same example with the latest version: http://jsfiddle.net/ycqhf3f8/
