### ISSUE TITLE
CSS selector for bar itself

### ISSUE THREAD

**Issue by ObjectiveTruth** [rzajac/angularjs-slider#65]
Fairly new to CSS/HTML but i can't figure out the selector for this part of the bar.

I've gotten all the other portions styled except this part (sorry crappy paint skillz, RED used for emphasis):

![screen shot 2015-05-31 at 5](https://cloud.githubusercontent.com/assets/1545001/7904060/527ace8c-07bc-11e5-8d36-bf5d000edbc8.png)

P.S. great library :+1:

**Comment by rzajac** [comment]
Thanks. This is what controls the color

https://github.com/rzajac/angularjs-slider/blob/master/rzslider.less#L24
