### ISSUE TITLE
ng-model-low, ng-model-high are really required

### ISSUE THREAD

**Issue by jitendersaini** [rzajac/angularjs-slider#66]
Hi!, It's really a great work  and I really liked the design of these sliders, while I was implementing these in my project, I seen that ng-model-high and ng-model-low values are not defined I guess for this widget, hence if you type some very high value in range textbox then slider really go outside the window. It will be really great if you can fix this or let me know the other solution out of that, My requirement is define a slider between 0-200 (lets assume) and ng-model is tied with a textbox instead of label and user will not be able to type in textbox below 0 or bigger no than 200, but he is allowed to type any no between 0-200 and in decimal also e.g. 198.9. One more thing the step is not accepted for decimal values less than 1, If I want slider to step with value 0.5 then it's not working.  

Thanks
Jitender

**Comment by lash7** [comment]
On-change of the text in the textbox broadcast the slider event 'rzSliderForceRender ' to re-render the slider without having it to go  out of the window. Read [Slider Events](https://github.com/rzajac/angularjs-slider#slider-events)  for more info

**Comment by jitendersaini** [comment]
Hi Iash,
Thanks for your valuable answer, It will be really great if you can share me the sample code to control this with rzSliderForceRender.
Thanks

**Comment by ValentinH** [comment]
Also for decimal values, you can use the translate function to display the model value as a decimal. For instance if you want to go between 0 and 10 with a 0.1 step, then you need to configure the slider values between 0 and 100 (with a step of 1) and then display the value as value/10.

**Comment by ValentinH** [comment]
Closed as no answer for 3 months. Comment to re-open....
