### ISSUE TITLE
Question: how to resize the blue circle of slider

### ISSUE THREAD

**Issue by mastermind1981** [rzajac/angularjs-slider#70]
Hi,

First of all, you have done a great work done here.

I want  to resize the blue circle on the borders of the selection but i could not find how to do it from the less file.

I have tried to change in the css file span.rz-bubble.top  and span.rz-pointer.width and height to 16 px but it looks ugly.

Thanks

**Comment by ValentinH** [comment]
You need to modify the less file. Once there you only need to edit the 2 following variables:
```less
@handleSize: 32px;
@handlePointerSize: 8px;
```
