### ISSUE TITLE
Question: is it possible to format the value of the tooltip of model and high 

### ISSUE THREAD

**Issue by mastermind1981** [rzajac/angularjs-slider#71]
Hi,

Is it possible to format the values of the attributes model and high shown in the tooltips on the top the selection sides?
If it is not possible could i hide the tooltips ?
Thank you

**Comment by ValentinH** [comment]
Yeap, you need to pass a function to the `rz-slider-translate` attribute. You can see the 4th example [here](http://rzajac.github.io/angularjs-slider/) that use the following  function to display the characters:
```js
$scope.alphabetTranslate = function(value)
{
    return alphabetArray[value].toUpperCase();
};
```
