### ISSUE TITLE
Set value inside ng-repeat

### ISSUE THREAD

**Issue by jeromemmiranda** [rzajac/angularjs-slider#72]
Hi, when i try to output a slider outside the looping div, its outputting the correct value.

But when i tried to put it inside ng-repeat, the blue circle always stay in the zero value. But when you click on it, the circle will move to the specified value. I hope you can help me on this one.

**Comment by preetampvp** [comment]
I am also having this issue

**Comment by ValentinH** [comment]
Could you please provide a fiddle showing this issue?

You can try to force redraw with rzSliderForceRender event:
```js
$scope.$broadcast('rzSliderForceRender');
```
