### ISSUE TITLE
Slider not engaging ... to min and max values

### ISSUE THREAD

**Issue by coomsie** [rzajac/angularjs-slider#73]
Hi,

thanks for the module, its great.

using in this wee imagery app, but cant get the app to engage the sliders to be a range with min and max values .. always starting at the one end.

[Imagery App](http://test.canterburymaps.govt.nz/webapps/HIR/)

just zoom in to use the app then some images will appear on the left ... notice the date filter .. click that and you will see a date range ... but the sliders are at one end.

I create this on init

`$scope.dateSlider = {
            min: 0,
            max: 0,
            ceil: 0,
            floor: 0
        };`

then change it once a data query comes back ...

I am using dates ..... unix ones....

so for labels ...
`
$scope.translate = function (value) {
            var _date = new Date(value);
            var _year = _date.getFullYear();
            return _year;
        };`

and when the data comes back i do this ...

`
   console.log('floor', Math.min.apply(Math, $scope.responseDates), 'ceil', Math.max.apply(Math, $scope.responseDates));

            $scope.dateSlider.floor = Math.min.apply(Math, $scope.responseDates);
            $scope.dateSlider.min = Math.min.apply(Math, $scope.responseDates);
            $scope.dateSlider.ceil = Math.max.apply(Math, $scope.responseDates);
            $scope.dateSlider.max = Math.max.apply(Math, $scope.responseDates);
`

Any thing I doing wrong?

**Comment by ValentinH** [comment]
Are you still experiencing this issue? If yes, could you provide a JSFiddle showing the issue with the minimum of code needed. You can fork this one: http://jsfiddle.net/pq7yr6d6/

**Comment by coomsie** [comment]
Cheers, yes still an issue

have created this, but it works! yah! bummer mine doesnt ....

though i need to recreate the ajax method some how ...

https://jsfiddle.net/63zqeuwc/30/

**Comment by ValentinH** [comment]
Do you have the same result than on this example (before clicking the init button): https://jsfiddle.net/63zqeuwc/31/ ?

If yes, this is probably a problem of scope $digest. What are you using for your AJAX call?

**Comment by coomsie** [comment]
b.t.w. I'm using AngularJS v1.2.16 - it that the issue?

**Comment by ValentinH** [comment]
I don't know but the example I provided above works with the 1.2.16: https://jsfiddle.net/63zqeuwc/46/

**Comment by ValentinH** [comment]
You can try to force the slider to render after you update your values using this: 
```js
$scope.$broadcast('rzSliderForceRender');
```

**Comment by coomsie** [comment]
mmmm,

I've updated the jsfiddle as close and I can to my code ...

https://jsfiddle.net/63zqeuwc/48/

it works! damn it!

but not on my site ...

http://test.canterburymaps.govt.nz/webapps/FIR/

**Comment by coomsie** [comment]
![2015-07-29 22_07_58-imagery register debug mode](https://cloud.githubusercontent.com/assets/125121/8955139/62bb4e92-363e-11e5-817b-a509b40f534a.png)

this is the first initial load of the values.,

**Comment by ValentinH** [comment]
OK I bet this is a sync problems, try this:
```js
$timeout(function() {
    $scope.$broadcast('rzSliderForceRender');
})
```

BTW, in your fiddle you use both `rzSliderForceRender` and `reCalcViewDimensions` but just know that `rzSliderForceRender` includes `reCalcViewDimensions`

**Comment by coomsie** [comment]
ok, ta ... try it .. doesn't work ... i'll keep looking....

**Comment by coomsie** [comment]
Gidday,

lol, have cracked the nut ...

it's because I hide the dates slider initially ...

when I unhide it permanantly it works .....

but if hidden, it doesnt work as expected.

**Comment by ValentinH** [comment]
Yeap I often have this problem when using a slider inside a dropdown or a
modal. You need to call the rzForceRender message once it is visible.

**Comment by coomsie** [comment]
Cheers for your help ...

yeah just trying that out now ... with success on third button but not as i would want ... will get there though ...

http://jsfiddle.net/63zqeuwc/67/
