### ISSUE TITLE
Step is not working using value from scope

### ISSUE THREAD

**Issue by phuyem** [rzajac/angularjs-slider#78]
Hello,

This one works
    <rzslider
     rz-slider-step="10"
    rz-slider-floor="priceSlider.floor"
    rz-slider-ceil="priceSlider.ceil"
    rz-slider-model="priceSlider.min"
   ></rzslider>

This one doesn't

    <rzslider
     rz-slider-step="priceSlider.step"
    rz-slider-floor="priceSlider.floor"
    rz-slider-ceil="priceSlider.ceil"
    rz-slider-model="priceSlider.min"
   ></rzslider>

Given
$scope.priceSlider = {
    min: 100,
    max: 180,
    ceil: 500,
    floor: 0,
    step:10
};

Thanks for the great plugin

**Comment by phuyem** [comment]
Fix it myself : 
Line 1029
      rzSliderStep: '@',  

=>

      rzSliderStep: '=?',

**Comment by bdteo** [comment]
Yes it doesn't work. Values become NaN and the slider gets stuck.

**Comment by ValentinH** [comment]
Could you please provide a JSFiddle showing the issue?

**Comment by phuyem** [comment]
hey folks, I already gave the fix , didn't I. See the 2nd post. 
Open the source file,

Line 1029
rzSliderStep: '@',

=>

  rzSliderStep: '=?',

Thanks

**Comment by ValentinH** [comment]
I think setting the rzSliderStep as a string attribute was on purpose because it was not supposed to be changed. Maybe for performance reason, the author didn't want to use Two-way model binding.

Changing it may break existing applications using the slider so it has to been think twice...

For now, you can simply use `{{}}` to interpolate your value like this:
```html
<rzslider
 rz-slider-step="{{ priceSlider.step }}"
rz-slider-floor="priceSlider.floor"
rz-slider-ceil="priceSlider.ceil"
rz-slider-model="priceSlider.min"
```

**Comment by colm-mcqs** [comment]
Live saved. Been banging my head against this issue for a day!

**Comment by ValentinH** [comment]
With #158, this problem will be gone.
