### ISSUE TITLE
Slider position not set on load

### ISSUE THREAD

**Issue by rcbgit** [rzajac/angularjs-slider#79]
Using angular-fullstack I am setting a slider with the scope value like so:

    $scope.sliderValue = 100;

and the markup:

            <rzslider rz-slider-model="sliderValue"
                rz-slider-floor="2"
                rz-slider-hide-limit-labels = "false"
                rz-slider-ceil="100"
                rz-slider-always-show-bar="true"></rzslider>

I am displaying the value of the slider on the page and it is correctly set to 100, but the slider position is stuck at 0 until i click on it, then it jumps up to where it's supposed to be.

**Comment by soee** [comment]
I can confirm this issue (using Angular 1.4.x).

**Comment by rcbgit** [comment]
I also see the slider render correctly when I resize.

Still no fix.  Let me know if you come up with anything.

Thanks!

**Comment by soee** [comment]
Hi @rcbgit,

as i mentioned before i am using it inside tabs (ui-bootstrap) so the tab content is loaded when we select tab and because of this the sliders aren't updated as they should i think. What i do is to use tab 'select' attribute to call my custom function:
```html
<tabset>
    <tab select="ctrl.broadcast()">
        <tab-heading>Heading</tab-heading>
        @include('_partials.form_tabs_general')
    </tab>
    ...
</tabset>
```
and in my controller:
```javascript
function broadcast() {
    setTimeout(function(){
        $scope.$broadcast('reCalcViewDimensions');
    }, 10);
}
```

In some cases it is better to use Angular's *$timeout* service instead of native setTimeout.

**Comment by bernardmoes** [comment]
I can also confirm this issue. 
It doesn't work in combination with the following Jquery:

$(document).ready(function () {
            $('.filterButton').click(function (e) {
                e.preventDefault();
                $('.filterButton').removeClass('on');
                $('.filterContent').slideUp('normal');
                if ($(this).next().is(':hidden') == true) {
                    $(this).addClass('on');
                    $(this).next().slideDown('normal');
                }
            });
            $('.filterContent').hide();
        });

I think the 'hide' method is causing problems

**Comment by bdteo** [comment]
I also experienced exactly what OP described. This repo however seems to be dead anyway.

**Comment by mansa-dev** [comment]
Yes same issue here. But repo seems to be abandoned

**Comment by ValentinH** [comment]
Indeed, using ```$scope.$broadcast('reCalcViewDimensions');``` is the solution. This problem is due that when the slider is instantiated, the view is not visible and so it cannot be rendered properly.

This particular problem with tabs is mentionned here: https://github.com/rzajac/angularjs-slider#slider-events .
I have also experienced the issue when using a slider inside a angular-ui dropdown.

**Comment by aphanor** [comment]
Hey guys, I am having the same issue and I tried adding $scope.$broadcast('reCalcViewDimensions'); but it didn't work. Here is live working example:

http://ec2-52-16-54-212.eu-west-1.compute.amazonaws.com/test.html

The slider is on page "2".

Am I doing anything wrong?

**Comment by ValentinH** [comment]
Please provide a Fiddle that present the strict minimum of your problem. I don't want to go visiting a random page which can contain anything (virus?)...

**Comment by aphanor** [comment]
Sure, here is an example on Codepen: http://codepen.io/anon/pen/QbJmja

**Comment by ValentinH** [comment]
There you go: http://codepen.io/ValentinH/pen/yNQKXR?editors=001

You had several Angular-related problem:
- first you were not calling the broadcast function of the MainCtrl correctly (you should use the controllerAs synthax btw).
- don't use setTimeout() but $timeout (https://coderwall.com/p/udpmtq/angularjs-use-timeout-not-settimeout)

Finally, in your example, it also works without wrapping the  `$scope.$broadcast('reCalcViewDimensions')` with $timeout but it depends on the step plugin sequencing. To be sure that it is always called after the view is shown, use $timeout so the broadcast is called in the next JS loop.

**Comment by aphanor** [comment]
Awesome, thanks a lot for your help, it's much appreciated!

**Comment by gpolyn** [comment]
Per the OP's use context, and attempting the fix proposed from Jul 29, this still doesn't work.

Failing an example with tabs, I warn others about this integration!

**Comment by ValentinH** [comment]
What do you want to do? If you want help, please provide a JSFiddle showing the issue...

**Comment by ValentinH** [comment]
Since I'm in a good mood today, there is you example:
**Slider inside Angular UI tabs:** http://jsfiddle.net/7w755fLv/

**Comment by gpolyn** [comment]
Yes, that does better address it, though the rendering is triggered by tab select and I think I notice the slider's correcting action, visually.

Based on review of Angular-UI Bootstrap tab issues, I might expect challenges for the embedding of any directive in tab content panes. Therefore, my proposal to anyone (perhaps it is already familiar to most) is to confirm their chosen tab directive works with any directives planned for use in tab panes.

**Comment by ValentinH** [comment]
You will get issues with any widgets that show/hide content dynamically such as tabs, popover or even ng-show. 
The problem is that the directive you place inside the content, such as this slider, does not have an efficient way to detect when it becomes visible. So if this directive needs to compute the width/height/position of its parent, you will need to trigger a refresh event manually.

**Comment by pushpendra18** [comment]
Hi All,

I have faced the same issue inside accordion my slider not initializing.
Finally ValentinH solution guide me in right path.
Below is the code.

Calling refreshSlider() in ng-click of the accordion div .

HTML:
<form name="myform">
        <div class="panel-group flatPannels filterGroup" id="accordion">

          

            <div class="panel panel-default filterStyle" ng-click="refreshSlider()">
                <div class="panel-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" data-target="#collapseFour">
                        <h4 class="panel-title">  myslider<i class="indicator glyphicon glyphicon-chevron-down pull-right"></i></h4>
                    </a>
                </div>
                <div id="collapseFour" class="panel-collapse collapse">
                    <div class="panel-body">
                        
                        <label class="title" ></label>

                        <div class="sliderInputWrapepr">
                           
                            <input type="number"
                                   placeholder="{{ 'enter'  }}"
                                   ng-change="chklim($event)"
                                   ng-minlength="1"
                                   ng-maxlength="3"
                                   ng-min="aslider.floor"
                                   ng-max="aslider.ceil"
                                   name="inputvalMax" class="sliderinput" ng-class="{'err-txtbox':!searchFilterForm.inputvalMax.$valid}" ng-model="aslider.value1" required /><br />

                        </div>
                        <rzslider rz-slider-floor="aslider.floor"
                                  rz-slider-ceil="aslider.ceil"
                                  rz-slider-model="aslider.value"
                                  rz-slider-step="1"
                                  rz-slider-always-show-bar="true"
                                  rz-slider-tpl-url="rzSliderTpl.html"
                                  rz-slider-on-change="searchval();"></rzslider>
                       
                    </div>

                </div>
            </div>


           
        </div> 
    </form>

Angular:

 $scope.refreshSlider = function () {
                    $timeout(function () {
                        $scope.$broadcast('rzSliderForceRender');
                    });
                };

**Comment by Luddinus** [comment]
With ng-if works, not with ng-show

**Comment by matortheeternal** [comment]
@Luddinus ng-if works but it doesn't maintain slider values after you hide and show it again.

**Comment by ValentinH** [comment]
If the slider is inside a div toggled with ng-if, it is destroyed on each hide:  this is normal since ng-if destroys its content.

You need to save the slider value in the parent's scope then or in a service.

**Comment by mjknight50** [comment]
Hi Valentin,
I have the same issue if you wouldn't mind taking a look, please?

https://jsfiddle.net/mjknight50/hmap4qj7/

You need to either widen your screen or pop-out the menu using the icon.

I have tried all of the suggestions I have seen you post so far, but the initial slider position isn't setting correctly until I resize the screen or until I click on the slider.

**Comment by ValentinH** [comment]
@mjknight50 You need to send the following event when the slider becomes visible:
```js
$scope.$broadcast('rzSliderForceRender');
```

I can't really help more because your example is complex and generating a lot of errors that are not linked to the slider.

**Comment by mjknight50** [comment]
Thanks Valentin... 
I added this, which fixed it:

  angular.element(document).ready(function () {
        $scope.$broadcast('rzSliderForceRender');
    });

**Comment by appernetic** [comment]
Same problem here, I have to try this solution!

2016-04-25 23:13 GMT+02:00 Matthew Knight <notifications@github.com>:

**Comment by maknapp** [comment]
For the ng-show and tab problems, I have looked into this further and have a solution that gets rid of any flickering. In angularjs v1.2, the slider did not require a timeout and could be force rendered immediately. [This](https://github.com/angular/angular.js/commit/667183a) is the breaking commit that defers ng-show until the end of the digest cycle.

So, running force render in post digest instead of JavaScript's next execution cycle (setTimeout) will get rid of any flickering ([jsfiddle](http://jsfiddle.net/8zg6rrn2/1/)):

    $scope.$$postDigest(function () {
        $scope.$broadcast('rzSliderForceRender');
    });

Also, if you want to continue using $setTimeout you should at least stop it from running digest again, since rzSliderForceRender does not require another digest:

    $timeout(function () {
        $scope.$broadcast('rzSliderForceRender');
    }, 0, false);

**Comment by ValentinH** [comment]
Thanks, this is really interesting! I'll add it to the README 👍

**Comment by marie-dk** [comment]
I am using uib-accordion and faced this issue. The solution that works for me, is to watch the is-open variable and render rzSlider on open.

In the slider controller:

```
$scope.accordion1.status = false;

$scope.$watch('accordion1.status', function(isOpen){
  if (isOpen) {
    $rootScope.$broadcast('rzSliderForceRender');
    console.log('accordion1 is open');
  }
});

```
And the accordion:
```
<uib-accordion close-others="true">
<uib-accordion-group is-open="accordion1.status">
    <uib-accordion-heading>
      <span>Hello world</span>
      </uib-accordion-heading>
      <p>
        <rzslider rz-slider-model="formData.weight"  rz-slider-options="wslider"></rzslider>
       </p>
     </uib-accordion-group>
</uib-accordion>
```

**Comment by ValentinH** [comment]
You probably don't need to broadcast on the whole $rootscope, $scope.$broadcast might be enough ;)

**Comment by Dreamerpro** [comment]
I got over this issue by increasing timeout delay to above 170ms.
	`$timeout(function () {
	     $scope.$broadcast('rzSliderForceRender');
	 },170);`

**Comment by ValentinH** [comment]
The issue is that the rendering time is browser dependant so it might be more on other browser/devices..

**Comment by niqt** [comment]
I tried any solutions but in uib-tab and uib-tabset, i have always the problem

**Comment by ValentinH** [comment]
Demo please. Btw there is an example of slider in uib-tab on the website...

**Comment by niqt** [comment]
Sorry but i in the demo find tab and tabset doesn't see ui-tab and ui-tabset did saw in wrong place?

**Comment by ValentinH** [comment]
This is just because the demo use on old version of ui-bootstrap where the uib- prefix wasn't mandatory. But the demo shows how to use uib-bootstrap tabs

**Comment by RogerBrad** [comment]
Thank you for your help.  Used this as described in the fiddle: http://jsfiddle.net/8zg6rrn2/1/

In the controller js:
    var vm = this;
    vm.refreshSlider = function () {
        $scope.$$postDigest(function () {
            $scope.$broadcast('rzSliderForceRender');
        });
    };

Called it from the ng-show function also in the controller js:

vm.refreshSlider();

**Comment by marcinn** [comment]
$postDigest nor $broadcast() workarounds does not work for me.  I'll try to provide fiddle someday.  
No chances to make corrent rendering without such tricks?

**Comment by ValentinH** [comment]
Unfortunately no, the library can't know when it become visible (or at least not without doing some dirty-checking) so you have to tell it (I usually use `$broadcast` inside a `$ timeout`).

**Comment by marcinn** [comment]
Thanks. I've double checked callback and found a typo. Sorry for disturbing.

**Comment by marcinn** [comment]
Unfortunatelly there are too many use cases, where refreshing is required. I have a controller which gets an event probably before rendering. It is hard to know when element becomes visible (rendered by browser engine). Maybe you can control it within a directive, but a view controller can't do that without checking DOM elements directly. This makes using the slider very hard and time-consuming. You should find other solution. Just my 5cents.

**Comment by ValentinH** [comment]
A solution like this: http://stackoverflow.com/a/31085644/1713469 could be doable but it's very heavy since that means angular will check the dom at each $digest iteration!
Also this answer: http://stackoverflow.com/a/1462510/1713469 summarizes what I have in mind... Your logic should be predictable so you should always know if the slider container is visible.

**Comment by marcinn** [comment]
I'm setting scope var to make container visible and directly after that I'm calling refresh event. It does not work probably due some race condition. Unfortunatelly I have no time to dig this issue today.

**Comment by rsrikanth080** [comment]
HI! I am using rzslider with controllerAs syntax. 

```
$timeout(function () {
      $scope.$broadcast('rzSliderForceRender');
    }, 10);
```
This doesnt work. how can i make it work with controllerAs syntax.

**Comment by ValentinH** [comment]
Please provide a demo showing the issue. There is no reason that using `controllerAs` syntax could be a cause of this issue.

**Comment by mjknight50** [comment]
@rsrikanth080  I am using controllerAs with no problem.   As @ValentinH said, if you have a more complete example, it would help.

Here is how I am doing that same block you listed:

  //in theory, only one of these should be needed, to force the render, but both are needed in my testing
    $timeout(function () { $scope.$broadcast('rzSliderForceRender'); }, 170);

    angular.element(document).ready(function () {
        $scope.$broadcast('rzSliderForceRender');
    });

**Comment by rsrikanth080** [comment]
@ValentinH @mjknight50 

Please check the issue here in one of my test server link - http://rnm.matrix.gmastesttest.com/category/219/two-seater/

After the page is loaded please click on price filter
![screen shot 2016-12-20 at 6 36 03 pm](https://cloud.githubusercontent.com/assets/5307643/21351583/40d9256a-c6e3-11e6-8bac-ceea7b63416d.png)

**Comment by ValentinH** [comment]
When do you call `$timeout`? BTW, we need code to understand what you do. The best so we can help you would be to create a JSFiddle only showing the issue and the code for it.

**Comment by rsrikanth080** [comment]
@ValentinH 
you can check in the category.js file 

http://rnm.matrix.gmastesttest.com/static/js/basefiles/category.js

**Comment by mjknight50** [comment]
@rsrikanth080 - Please be considerate of our time.  Searching through your source code to help you isn't ideal.  A JSFiddle would be better and would probably also help you by isolating the issue.

**Comment by ValentinH** [comment]
Please, I won't help you if you don't provide materials! I'm not supposed to go and read all your code, people are are contributing on their free time. If you want enterprise support, then pay somebody for that.

**Comment by ValentinH** [comment]
However, your issue is probably due to the fact the you must call `rzSliderForceRender` after your popup is shown (as done on the uib-modal demo on our demo page).

**Comment by mjknight50** [comment]
I agree with @ValentinH; the issue is that when your shopService comes back with prices, you must then call rzSliderForceRender to reinitialize the slider.  You can use my sample code from above to do this rendering.

**Comment by rsrikanth080** [comment]
Sure guys! Will make a fiddle and share. @ValentinH so m not using any popup. its just a block which i show and hide on hover of other elements. dom is being created just like other elements.

**Comment by marcinn** [comment]
As I said earlier - depending on rzSliderForceRender IS a workaround and it causes more problems than benefits it gives (a nice look). Drawing/positioning a slider should be done other way.

**Comment by ValentinH** [comment]
@marcinn Yes it's a workaround but even after mor ethan a year maintaining this libary I couldn't find a better solution... Again contributions are always welcome.

@rsrikanth080 I said "popup", but I just meant to you should call `rzSliderForceRender` after you show the slider.

**Comment by rsrikanth080** [comment]
@ValentinH - https://jsfiddle.net/0wa8Lyj5/1/

**Comment by ValentinH** [comment]
A few problems there: 
1) there is no `rz-slider-step attribute` in this library, you should set the `step` in the options
2) you swap floor and ceil values

Demo: https://jsfiddle.net/syxa1k0r/

**Comment by rsrikanth080** [comment]
@ValentinH @mjknight50 Its working, As you guys suggested show trigger broadcast when the slider is in visible dom. Thanks guys. I apologize for the stupid question.

**Comment by ValentinH** [comment]
No worries it's always good to learn and no question is stupid while learning! :)

**Comment by lu-ctrl-z** [comment]
I have same issue but here my solution.

CSS:
.tab-content.fixTabsAndSlider > .tab-pane{
	display: block;
	height: 0px;
	overflow: hidden;
}
.tab-content.fixTabsAndSlider > .tab-pane.active{
	display: block;
	height: auto;
	overflow: visible;
}
html:
<div class="tab-content fixTabsAndSlider">
...
</div>

**Comment by johnico** [comment]
happens to me when fade in and fade out the page also with your examples 

https://github.com/angular-slider/angularjs-slider/issues/515

**Comment by ValentinH** [comment]
Did the fix mentioned above work for you?

**Comment by jdwilemo** [comment]
I have a uib-carousel with a slider in each slide as part of an HTML template, and while the sliders are rendering properly, I am getting a slow drag into each slide instead of a snappy switch. 

In order to force rerender the slide, I call the timeout on each slide click like so:
<div uib-carousel ng-click="$ctrl.refreshSlider()">

My refresh function is:
this.refreshSlider = function() {
      var $ctrl = this;
      this._$scope.$$postDigest(function () {
        $ctrl._$scope.$broadcast('rzSliderForceRender')
      });
    }

I only have around 20 total controls, but is this due to the slide waiting for all sliders to rerender? Is there a better way of force refreshing sliders when you are dealing with many of them in one page?

**Comment by ValentinH** [comment]
If all sliders are on the same scope, you can't target one specifically when broadcasting the `rzSliderForceRender` event. You can be more accurate by isolating each slider in its own scope (via a directive) and only broadcast the event on the specific scope.

**Comment by ValentinH** [comment]
However, I don't think the performance issue comes from the sliders for the following reason: on the demo site, there are more than 30 sliders and I use the refresh on the whole scope in the tas demo and it's not slow...

**Comment by jdwilemo** [comment]
@ValentinH thanks for the suggestions. 
I now think it had to do with using the ng-click on the carousel control. I've gotten it to render the controls correctly with no slide lag by doing the following:

```
this._$scope.$watch(function watchSlides(_$scope){
      return (_$scope.$ctrl.active);
    },
    function handleSlideChange(oldVal, newVal, scope){
      console.log('Id changed to ' + newVal + ' from ' + oldVal);
      scope.$ctrl.refreshSlider();
    });

this.refreshSlider = function() {
      var $ctrl = this;
      this._$timeout(function () {
        $ctrl._$scope.$broadcast('rzSliderForceRender')
      });
    }
```

In the case someone else has a nested mess like I do.

**Comment by ValentinH** [comment]
Good to know. Just a little question, why can't you do `this.$scope.$watch('$ctrl.active', fn)`?

**Comment by jdwilemo** [comment]
You can if you're only watching one "active" state, but that example is a watered down version of my handleSlideChange which had to watch several dynamic slide + tab combination states. I wasn't sure how to put a watch on only that without breaking it down in the function.

**Comment by ValentinH** [comment]
OK I get it.

**Comment by ianldgs** [comment]
I have inserted a `debugger;` in the `$on('rzSliderForceRender')` and found that the problem is with `resetSlider() -> calcViewDimensions() -> getDimension() -> getBoundingClientRect()`. It returns `0` on the properties if the element **or parent** is hidden.

![image](https://user-images.githubusercontent.com/6526498/28325666-d33eaa3a-6bb4-11e7-886a-5c5e812ead59.png)

One possible solution is to rely on jQuery, as it does some magic to get the dimensions even if the element is hidden.

Other possible solution is to implement the jQuery magic: 
https://stackoverflow.com/a/33194373/2502746
https://github.com/jquery/jquery/blob/master/src/css.js#L344

For now, solved by broadcasting rzSliderForceRender. But even inside a `$timeout`, the `$broadcast` is called before my element showing up on screen.

**Comment by ValentinH** [comment]
I have never met a case where `$timeout` wasn't enough. If you can provide a demo showing this behaviour, it would be nice.

About the first part of your question, I agree that having to force the rendering is quite annoying and a big source of issues (see the length of this thread). It might be a good idea to use the trick you mentioned when getBoundingClientRect returns width/height = 0.

Do you think you can provide a pull request for this improvement? 🙂

**Comment by nitingupta4040** [comment]
Hello Everyone,
I tried all options but scale is not rendering properly. The only thing which worked was  $timeout(function () {
      $scope.$broadcast('rzSliderForceRender');
    }, 10);. But i do not want to set the time in timeout. Is there a way around?

**Comment by ZtheLeader** [comment]
In my case, I used this in my Controller
`    $scope. loadView = function(){
        setTimeout(function(){
            $scope.$broadcast('rzSliderForceRender');
        },1);
    }`

And the in my View (I'm not using `tab-ui`), I use it as:
` <div ng-init="loadView()">
                  <rzslider
                          rz-slider-model="color_slider_pointer.value"
                          rz-slider-options="color_slider_pointer.options">
                  </rzslider>`

And It works like charm!

**Comment by farisabun** [comment]
Hi, I tried change `ng-show` to `ng-if` and insert this to my init code:

> `angular.element(document).ready(function () {
>                 $scope.$broadcast('rzSliderForceRender');
>             });`
