### ISSUE TITLE
Set value not only by slide, but also with click/touch on track

### ISSUE THREAD

**Issue by radek-anuszewski** [rzajac/angularjs-slider#82]
Hi! 

I found **rzslider** very useful and easy customizable (I needed some changes in CSS and it was very easy) especially in mobile devices (in contrast to [AngularUI Slider](http://angular-ui.github.io/ui-slider/demo/demo.html), which requires [Touch punch workaround](http://stackoverflow.com/a/9533878/3368498), but it might [not work on Windows devices](http://stackoverflow.com/a/22035161/3368498)). But I think one feature is missing in **rzslider**: in contrast to [AngularUI Slider](http://angular-ui.github.io/ui-slider/demo/demo.html) I can't click on *slider track* to set value. Are there plans to add this functionality in future?

Greetings!

**Comment by ValentinH** [comment]
I submitted a pull request for it some weeks ago: #69

**Comment by ValentinH** [comment]
It is now available on master ;)
