### ISSUE TITLE
Question: How can create array of steps?

### ISSUE THREAD

**Issue by rubinchyk** [rzajac/angularjs-slider#85]
Hi.
Can you explain to me. How I can create an array of steps. 
For example I have this code: 
    $scope.sensitivity = {
        min: 10,
        max: 50,
        default: 10
    };

I need fixed points like [10----20----50].
How can I do this?

**Comment by ValentinH** [comment]
You can do this by using a custom translate function. The slider will be picking an index of your array and you will need to handle the link with the array.

```html
<rzslider
    rz-slider-floor="yourSlider.floor"
    rz-slider-ceil="yourSlider.ceil"
    rz-slider-model="yourSlider.model"
    rz-slider-translate="translate"></rzslider>
```

```js
var yourValues = [10, 25, 50, 80, 1000]; //obviously heterogeneous

$scope.yourSlider = {
	value: 0,
    floor: 0,
    ceil: yourValues.length - 1,
    step: 1
};

$scope.translate = function(index)
{
    if(index >= 0 && index < yourValues.length)
    	return yourValues[index];
    return ''; //error case
};

//then to get the selected value (you can set a watch to react on each change or use this #67 if it gets merged)
var selectedValue = yourValues[$scope.yourSlider.value];
```

**Comment by rubinchyk** [comment]
Thank you

**Comment by Duncan2692** [comment]
How could I output a string value 
`stepsArray:'one,two,three'`
Into an html <input> similar to the "Simple Slider" works?

**Comment by ValentinH** [comment]
Sorry but I don't understand what you want...

**Comment by Duncan2692** [comment]
Sorry, I'll attempt to explain a different way...

Currently, the 'Simple Slider' displays its value in the 'Model:` <input>`' field as illustrated in this picture below
http://i.imgur.com/4hqBTWz.png

I want to create the same for the 'Alphabet Slider' where there is no 'Model:' box? 

How would i do this?

**Comment by ValentinH** [comment]
Hmm you can't do this since the value handled by the slider in this case is an index in an array, not the displayed value.

**Comment by Duncan2692** [comment]
Oh ok, thank you for your time anyway. 
If you do think of a way to get the array value, please do share :-)

**Comment by ValentinH** [comment]
Getting the array value is easy, just access it with the index. The problem is to bind it to a text input...
