### ISSUE TITLE
slideEnded event: not possible to get the rzslider html element

### ISSUE THREAD

**Issue by festivalhopper** [rzajac/angularjs-slider#86]
There seems to be no possibility to get the rzslider html element when reacting on a slideEnded event. The event variable does not contain any useful information about the slider element.
I wanted to change the opacity of the slider when a user moves a specific slider. Here's my workaround: I changed the $emit of this event from:
Original code: this.scope.$emit("slideEnded")
to:
Updated code: this.scope.$emit("slideEnded", this)

In my eventhandling function I am now able to get the id of the slider element like this:
$scope.$on("slideEnded", function(event, args) {
    	var compositeSliderId = args.attributes.id;
        ...
});

Question: Is there another possibility to do this that I overlooked? If no, do you think it's feasible to integrate my workaround?

**Comment by festivalhopper** [comment]
On a sidenote: emitting a slideStarted event would be nice too, just for completion's sake.

**Comment by radek-anuszewski** [comment]
To achevie this, merge [rzSliderOnChange attribute](https://github.com/rzajac/angularjs-slider/pull/67) could be helpful.

**Comment by adambarthelson** [comment]
+1

**Comment by ValentinH** [comment]
There is now a on-start and on-end callback that can be used as the on-change one. ;)

**Comment by festivalhopper** [comment]
that's great, thank you, will check it out next week.
