### ISSUE TITLE
Ability to show all available values 

### ISSUE THREAD

**Issue by nikshulipa** [rzajac/angularjs-slider#89]
Is it possible to show all available values to select? (e.g. when we have slider from 0 to 10, it will show us all options, not first and last only)

**Comment by ValentinH** [comment]
With the current version, it is not possible. Also, the code only handles displaying limits values and current value, it wasn't think to display all of them. So it would be quite complicated to implement it. 

There is a PR ( #68 )  that add ticks displays on the slider that might approach what you wanna do.

**Comment by nikshulipa** [comment]
Ok, got it.
I saw it, but it shows ticks and not values.

Maybe, you can suggest right way to implement this?

**Comment by ValentinH** [comment]
As I said it is quite complicated because you need to add an DOM element for each value, giving it the correct value, correct position (it might depends on the value width)... You can check how I implemented the ticks to get some clues.

**Comment by nikshulipa** [comment]
hmm....
anyway, thanks!
