### ISSUE TITLE
Feature : Intervals ?

### ISSUE THREAD

**Issue by bksoux** [rzajac/angularjs-slider#91]
Hi. Great work ;) 
Do you think it would be possible to have a multi range (like intervals) slider ?

**Comment by ValentinH** [comment]
I don't really see what you mean, do you have an example?

**Comment by bksoux** [comment]
Sorry, like this for example : http://jsfiddle.net/q5WEe/1/

**Comment by ValentinH** [comment]
Unfortunately it is not possible currently. Any PR would be welcome but I think it is rather complicated to implement it on the current version.

**Comment by bksoux** [comment]
ok thanks i'll try to do something
