### ISSUE TITLE
Bug with updating value in parent scope when using range

### ISSUE THREAD

**Issue by nikshulipa** [rzajac/angularjs-slider#93]
Steps to reproduce:
1) go to the http://rzajac.github.io/angularjs-slider/
2) manually update first slider: min value to new position(e.g. 308), and max value to the same position (308). Numbers here is just an example, the restrictions are: min and max should be the same and it will be different from previous values

Expected result: 
model values in inputs should match (in my example both equal to 308)

Actual result: 
model values isn't match

only when you try to move another slider, model values will updated

Screenshot:
<img width="962" alt="screen shot 2015-07-27 at 5 34 38 pm" src="https://cloud.githubusercontent.com/assets/1872256/8908834/ebf47634-3486-11e5-8332-de4d50676506.png">

Workaround which I found for now is to force `$digest` using `slideEnded` event in parent scope, e.g.
```
    $scope.$on("slideEnded", function() {
        $scope.$digest();
    });
```

**Comment by ValentinH** [comment]
Again, well spotted!
