### ISSUE TITLE
Bug with wrong rz-selection positioning

### ISSUE THREAD

**Issue by nikshulipa** [rzajac/angularjs-slider#94]
Steps to reproduce: 
1) go to the http://rzajac.github.io/angularjs-slider/
This bug will be shown on first slider but you can reproduce it on any slider with range 
    (when `rz-slider-high` is selected)
2) hold right selector point and drag in to the left part so the right selectors will become left selectors and vice versa
OR
move left selector point so it will always stays on the left regarding to the right selector point
3) click on the slider line at the most right position

Expected result:
selection line will be between two selector points

Actual result:

<img width="1416" alt="screen shot 1" src="https://cloud.githubusercontent.com/assets/1872256/8909371/aca0e294-3489-11e5-8c90-75599798276f.png">

If you scroll page on x to the right, you will see something like this:

<img width="1002" alt="screen shot 2015-07-27 at 5 55 58 pm" src="https://cloud.githubusercontent.com/assets/1872256/8909384/be361092-3489-11e5-9ad5-8f4817050347.png">

**Comment by ValentinH** [comment]
Well spotted! I'll investigate.
