### ISSUE TITLE
some absolute elements dont declare left attribute, in some context the layout will crash

### ISSUE THREAD

**Issue by e-cloud** [rzajac/angularjs-slider#97]

**Comment by ValentinH** [comment]
Could you provide a JSFiddle showing the problem? (starting from this one if you want http://jsfiddle.net/pq7yr6d6/)

**Comment by e-cloud** [comment]
http://jsfiddle.net/hbff1om5/1/ i distract some of my src to reproduce the case

**Comment by ValentinH** [comment]
Fixed by b405f126b425f
