### ISSUE TITLE
[feat] disable value labels

### ISSUE THREAD

**Issue by santyclaz** [rzajac/angularjs-slider#99]
Hey guys, great work on this directive! I love it when I drop in a directive and it just works.

This is just a simple feature request to add another attribute to easily disable the value label. I know I can already achieve the same affect by providing a translate function that returns an empty string, but it would be nice to have a simple way to enable/disable this.

In case you're wondering, I'm managing the display of the high/low model values myself in the app, so I that's why I don't need the value labels.

Cheers

**Comment by ValentinH** [comment]
There is an option to hide the min/max value (`rz-slider-hide-limit-labels`) but not for the current value.
For now, you can simply hide them with CSS:  http://jsfiddle.net/hayaqsrx/

**Comment by soee** [comment]
+1 for this request. I do not like to hide some elements via css when we could just disable it :)

**Comment by ValentinH** [comment]
I understand your point but I don't really like to overload this directive with code that can be replaced by CSS...

**Comment by RabidDog** [comment]
The problem is that via CSS is disables all labels, certain use cases require just the slider value be hidden.

**Comment by ValentinH** [comment]
It was true at the time of my comment but now you can target it by selecting .rz-bubble and not .rz-limit... 

Anyway, now there is a hidePointerLabels option. ;)

**Comment by MyronRogtao** [comment]
Is there a way to disable a specific handle? Either min-handle or max-handle, based on some condition?

**Comment by ValentinH** [comment]
At the moment no,  there is no such option.

**Comment by MyronRogtao** [comment]
The use case was to define multiple range tiers using slider such that after defining the range for one tier, the slider min-handle must be fixed to the max of the previously defined tier and max will be pointing to ceiling value. We can then deine the next tier by only moving thr max-handle.

Found a way to disable the movement of the min handle using the onStart event and the minRange value. Manipulate the minrange value based on the pointer type in the onStart event.
